CREATE TABLE "conditions"."source" (
	"id" text PRIMARY KEY NOT NULL,
	"domain" text NOT NULL,
	"format" text NOT NULL,
	"produces" text NOT NULL,
	"access_mode" text NOT NULL,
	"tier" text NOT NULL,
	"country" text NOT NULL,
	"subdivision" text,
	"operator" text NOT NULL,
	"license" text NOT NULL,
	"license_url" text,
	"attribution" text NOT NULL,
	"rights" jsonb,
	"cadence_sec" integer NOT NULL,
	"freshness_window_sec" integer NOT NULL,
	"raw_retention" text,
	"extras_allow" text[] DEFAULT '{}'::text[] NOT NULL,
	"extras_federate" boolean DEFAULT false NOT NULL,
	"lane_numbering" text,
	"parent_source_id" text,
	"policy_ids" text[],
	"selection_state" text,
	"active" boolean DEFAULT true NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "source_access_mode_enum" CHECK ("access_mode" IN ('bulk', 'on_demand')),
	CONSTRAINT "source_tier_enum" CHECK ("tier" IN ('authoritative', 'operator', 'aggregator', 'community')),
	CONSTRAINT "source_produces_enum" CHECK ("conditions"."source"."produces" IN ('events', 'flow'))
);
