/**
 * Roads classification → emitter vocabularies. Keys are situation codes
 * `kind.type[.subtype]`; an emitter takes the most specific entry (subtype,
 * then type). Every registered `kind.type` has an entry; `null` marks a type
 * the target cannot represent, which that emitter then leaves out.
 */
export const TRAFF_EVENTS: Readonly<Record<string, string | null>> = {
  "incident.accident": "INCIDENT_ACCIDENT",
  "incident.accident.multi_vehicle": "INCIDENT_MULTI_VEHICLE_ACCIDENT",
  "incident.accident.jackknifed_truck": "INCIDENT_JACKKNIFED_HGV",
  "incident.accident.overturned": "INCIDENT_OVERTURNED_VEHICLE",
  "incident.accident.bus_involved": "INCIDENT_BUS_ACCIDENT",
  "incident.accident.heavy_vehicle_involved": "INCIDENT_HGV_ACCIDENT",
  "incident.accident.hazmat_spill": "INCIDENT_HAZMAT_ACCIDENT",
  "incident.accident.secondary": "INCIDENT_SECONDARY_ACCIDENT",
  "incident.accident.fatal": "INCIDENT_SERIOUS_ACCIDENT",
  "incident.breakdown": "INCIDENT_BROKEN_DOWN_VEHICLE",
  "incident.breakdown.wrong_way_driver": "HAZARD_WRONG_WAY_DRIVER",
  "incident.vehicle_hazard": "HAZARD_OBSTRUCTION",
  "incident.vehicle_hazard.slow_vehicle": "HAZARD_SLOW_VEHICLE",
  "incident.vehicle_hazard.abnormal_load": "HAZARD_ABNORMAL_LOAD",
  "incident.vehicle_hazard.oversize_vehicle": "HAZARD_OVERHEIGHT_LOAD",
  "incident.vehicle_hazard.hazmat_vehicle": "HAZARD_HAZMAT",
  "incident.vehicle_hazard.emergency_vehicle": "HAZARD_EMERGENCY_VEHICLE",
  "incident.vehicle_hazard.maintenance_vehicle": "HAZARD_SLOW_MOVING_MAINTENANCE",
  "incident.vehicle_hazard.reckless_driver": "HAZARD_RECKLESS_DRIVER",
  "incident.vehicle_hazard.high_speed_chase": "HAZARD_HIGH_SPEED_CHASE",
  "incident.vehicle_hazard.unlit_vehicle": "HAZARD_UNLIT_VEHICLE",
  "incident.vehicle_hazard.prohibited_vehicle": "HAZARD_PROHIBITED_VEHICLE",
  "incident.obstruction": "HAZARD_OBSTRUCTION",
  "incident.obstruction.fallen_tree": "HAZARD_FALLEN_TREE",
  "incident.obstruction.landslide": "HAZARD_LANDSLIPS",
  "incident.obstruction.rockfall": "HAZARD_ROCKFALLS",
  "incident.obstruction.spill": "HAZARD_SPILLAGE",
  "incident.obstruction.object": "HAZARD_OBJECT_ON_ROAD",
  "incident.obstruction.animal": "HAZARD_ANIMALS_ON_ROAD",
  "incident.obstruction.people_on_road": "HAZARD_PEOPLE_ON_ROAD",
  "incident.obstruction.sinkhole": "HAZARD_SUBSIDENCE",
  "incident.fire": "HAZARD_SERIOUS_FIRE",
  "incident.fire.vehicle_fire": "INCIDENT_VEHICLE_FIRE",
  "roadworks.works": "CONSTRUCTION_ROADWORKS",
  "roadworks.works.maintenance": "CONSTRUCTION_MAINTENANCE",
  "roadworks.works.resurfacing": "CONSTRUCTION_RESURFACING_WORK",
  "roadworks.works.construction": "CONSTRUCTION_CONSTRUCTION_WORK",
  "roadworks.works.demolition": "CONSTRUCTION_DEMOLITION_WORK",
  "roadworks.works.blasting": "CONSTRUCTION_BLASTING",
  "roadworks.works.emergency_repair": "CONSTRUCTION_REPAIR",
  "roadworks.works.line_marking": "HAZARD_ROAD_MARKING_WORK",
  "closure.closure": "RESTRICTION_CLOSED",
  "closure.closure.carriageway": "RESTRICTION_CARRIAGEWAY_CLOSED",
  "closure.closure.ramp": "RESTRICTION_RAMP_CLOSED",
  "closure.closure.lane": "RESTRICTION_LANE_CLOSED",
  "closure.closure.bridge": "RESTRICTION_BRIDGE_CLOSED",
  "closure.closure.tunnel": "RESTRICTION_TUNNEL_CLOSED",
  "closure.closure.intermittent": "RESTRICTION_INTERMITTENT_CLOSURES",
  "restriction.dimension": "RESTRICTION_RESTRICTIONS",
  "restriction.dimension.height": "RESTRICTION_MAX_HEIGHT",
  "restriction.dimension.width": "RESTRICTION_MAX_WIDTH",
  "restriction.dimension.length": "RESTRICTION_MAX_LENGTH",
  "restriction.dimension.weight": "RESTRICTION_MAX_WEIGHT",
  "restriction.dimension.axle_load": "RESTRICTION_MAX_AXLE_LOAD",
  "restriction.access": "RESTRICTION_RESTRICTIONS",
  "restriction.access.no_overtaking": "RESTRICTION_NO_OVERTAKING",
  "restriction.access.low_emission_zone": "RESTRICTION_LOW_EMISSION_ZONE",
  "restriction.access.convoy": "RESTRICTION_CONVOY_SERVICE_REQUIRED",
  "restriction.access.hov": "RESTRICTION_USE_CARPOOL_LANE",
  "restriction.speed": "RESTRICTION_SPEED_LIMIT",
  "restriction.seasonal_load": "RESTRICTION_MAX_WEIGHT",
  "winter_operation.chain_control": "RESTRICTION_RESTRICTIONS",
  "weather_condition.weather": "HAZARD_HAZARDOUS_CONDITIONS",
  "weather_condition.weather.ice": "HAZARD_ICE",
  "weather_condition.weather.snow": "WEATHER_SNOWFALL",
  "weather_condition.weather.freezing_rain": "HAZARD_FREEZING_RAIN",
  "weather_condition.weather.rain": "WEATHER_RAIN",
  "weather_condition.weather.heavy_rain": "WEATHER_HEAVY_RAIN",
  "weather_condition.weather.hail": "WEATHER_HAIL",
  "weather_condition.weather.fog": "WEATHER_FOG",
  "weather_condition.weather.high_wind": "WEATHER_STRONG_WIND",
  "weather_condition.weather.storm": "WEATHER_STORM",
  "weather_condition.weather.thunderstorm": "WEATHER_THUNDERSTORM",
  "weather_condition.weather.dust": "WEATHER_BLOWING_DUST",
  "weather_condition.weather.black_ice": "HAZARD_BLACK_ICE",
  "weather_condition.weather.blizzard": "WEATHER_BLIZZARD",
  "weather_condition.weather.extreme_heat": "WEATHER_EXTREME_HEAT",
  "weather_condition.weather.extreme_cold": "WEATHER_EXTREME_COLD",
  "weather_condition.weather.low_sun": "WEATHER_LOW_SUN_GLARE",
  "weather_condition.weather.reduced_visibility": "WEATHER_REDUCED_VISIBILITY",
  "weather_condition.weather.pollution": "ENVIRONMENT_SMOG",
  "road_condition.surface": "HAZARD_SLIPPERY_ROAD",
  "road_condition.surface.icy": "HAZARD_ICE",
  "road_condition.surface.snow_covered": "HAZARD_SNOW_ON_ROAD",
  "road_condition.surface.slush": "HAZARD_SLUSH",
  "road_condition.surface.standing_water": "HAZARD_SURFACE_WATER",
  "road_condition.surface.mud": "HAZARD_MUD_ON_ROAD",
  "road_condition.surface.oil": "HAZARD_OIL_ON_ROAD",
  "road_condition.surface.loose_chippings": "HAZARD_LOOSE_CHIPPINGS",
  "road_condition.surface.gravel": "HAZARD_LOOSE_SAND_ON_ROAD",
  "road_condition.surface.leaves": "HAZARD_LEAVES_ON_ROAD",
  "road_condition.surface.rough": "HAZARD_BAD_ROAD",
  "road_condition.driving_condition": "HAZARD_DIFFICULT_CONDITIONS",
  "road_condition.driving_condition.impassable": "HAZARD_IMPASSABLE",
  "road_condition.driving_condition.hazardous": "HAZARD_HAZARDOUS_CONDITIONS",
  "road_condition.driving_condition.fair": "HAZARD_PASSABLE_WITH_CARE",
  "road_condition.driving_condition.good": "HAZARD_PASSABLE",
  "road_hazard.hazard": "HAZARD_HAZARDOUS_CONDITIONS",
  "road_hazard.hazard.avalanche_risk": "HAZARD_AVALANCHE_RISK",
  "road_hazard.hazard.flooding": "HAZARD_FLOODING",
  "road_hazard.hazard.high_water": "HAZARD_FLOODING",
  "road_hazard.hazard.wildfire_near_road": "HAZARD_FOREST_FIRE",
  "road_hazard.hazard.smoke": "WEATHER_SMOKE_HAZARD",
  "road_hazard.hazard.wildlife": "HAZARD_LARGE_ANIMALS_ON_ROAD",
  "public_event.event": "ACTIVITY_EVENT",
  "public_event.event.sporting": "ACTIVITY_SPORTS_EVENT",
  "public_event.event.parade": "ACTIVITY_PARADE",
  "public_event.event.concert": "ACTIVITY_CONCERT",
  "public_event.event.demonstration": "ACTIVITY_DEMONSTRATION",
  "public_event.event.market": "ACTIVITY_MARKET",
  "public_event.event.festival": "ACTIVITY_FESTIVAL",
  "public_event.event.exhibition": "ACTIVITY_EXHIBITION",
  "public_event.event.filming": "ACTIVITY_FILM_TV_PRODUCTION",
  "public_event.event.procession": "ACTIVITY_PROCESSION",
  "public_event.event.state_visit": "ACTIVITY_STATE_OCCASION",
  "authority.operation": "AUTHORITY_CHECKPOINT",
  "authority.operation.police_activity": "AUTHORITY_INVESTIGATION",
  "authority.operation.escort": "AUTHORITY_VIP_PASSING",
  "authority.operation.enforcement": "AUTHORITY_SPEED_CHECKS",
  "authority.operation.military_convoy": "HAZARD_MILITARY_CONVOY",
  "equipment_fault.fault": null,
  "equipment_fault.fault.traffic_signal": "EQUIPMENT_STATUS_TRAFFIC_LIGHTS_NOT_WORKING",
  "equipment_fault.fault.vms": "EQUIPMENT_STATUS_MESSAGE_SIGNS_NOT_WORKING",
  "equipment_fault.fault.tunnel_system": "EQUIPMENT_STATUS_TUNNEL_VENTILATION_NOT_WORKING",
  "equipment_fault.fault.emergency_phone": "EQUIPMENT_STATUS_EMERGENCY_PHONES_NOT_WORKING",
  "equipment_fault.fault.level_crossing": "EQUIPMENT_STATUS_LEVEL_CROSSING_NOT_WORKING",
  "equipment_fault.fault.toll_system": "EQUIPMENT_STATUS_AUTOMATIC_TOLL_SYSTEM_NOT_WORKING",
  "equipment_fault.fault.power": "EQUIPMENT_STATUS_POWER_FAILURE",
  "security.incident": "SECURITY_INCIDENT",
  "security.incident.bomb_alert": "SECURITY_BOMB_ALERT",
  "security.incident.evacuation": "SECURITY_EVACUATION",
  "security.incident.civil_unrest": "ACTIVITY_PUBLIC_DISTURBANCE",
  "pass_status.pass": null,
  "pass_status.pass.open": "RESTRICTION_OPEN",
  "pass_status.pass.closed": "RESTRICTION_CLOSED",
  "pass_status.pass.restricted": "RESTRICTION_RESTRICTIONS",
  "congestion.congestion": "CONGESTION_TRAFFIC_CONGESTION",
  "congestion.congestion.queuing": "CONGESTION_QUEUE",
  "congestion.congestion.stationary": "CONGESTION_STATIONARY_TRAFFIC",
  "congestion.congestion.stop_and_go": "CONGESTION_QUEUE",
  "congestion.congestion.heavy": "CONGESTION_HEAVY_TRAFFIC",
  "congestion.congestion.slow": "CONGESTION_SLOW_TRAFFIC",
  "other.other": null,
};

/** Roads classification → GTFS-Realtime `Alert.Cause` (road situations affecting transit). */
export const GTFS_RT_CAUSES: Readonly<Record<string, string | null>> = {
  "incident.accident": "ACCIDENT",
  "incident.breakdown": "OTHER_CAUSE",
  "incident.vehicle_hazard": "OTHER_CAUSE",
  "incident.obstruction": "OTHER_CAUSE",
  "incident.fire": "OTHER_CAUSE",
  "roadworks.works": "CONSTRUCTION",
  "roadworks.works.maintenance": "MAINTENANCE",
  "closure.closure": "OTHER_CAUSE",
  "restriction.dimension": "OTHER_CAUSE",
  "restriction.access": "OTHER_CAUSE",
  "restriction.speed": "OTHER_CAUSE",
  "restriction.seasonal_load": "OTHER_CAUSE",
  "winter_operation.chain_control": "WEATHER",
  "weather_condition.weather": "WEATHER",
  "road_condition.surface": "WEATHER",
  "road_condition.driving_condition": "WEATHER",
  "road_hazard.hazard": "WEATHER",
  "public_event.event": "OTHER_CAUSE",
  "public_event.event.demonstration": "DEMONSTRATION",
  "authority.operation": "POLICE_ACTIVITY",
  "equipment_fault.fault": "TECHNICAL_PROBLEM",
  "security.incident": "OTHER_CAUSE",
  "pass_status.pass": "WEATHER",
  "congestion.congestion": "OTHER_CAUSE",
  "other.other": "UNKNOWN_CAUSE",
};

/**
 * Roads classification → Road511/NAPSPAN `type/sub_type`, for consumers
 * migrating from those APIs. Road511 publishes no fixed list, so these codes
 * come from its live responses.
 */
export const ROAD511_TYPES: Readonly<Record<string, string | null>> = {
  "incident.accident": "incident/accident",
  "incident.breakdown": "incident/disabled_vehicle",
  "incident.vehicle_hazard": "incident/disabled_vehicle",
  "incident.obstruction": "hazard/debris",
  "incident.obstruction.spill": "hazard/spill",
  "incident.obstruction.animal": "hazard/animal",
  "incident.fire": "incident/fire",
  "roadworks.works": "construction/roadwork",
  "roadworks.works.maintenance": "construction/maintenance",
  "roadworks.works.bridge_work": "construction/bridge_work",
  "roadworks.works.utility_work": "construction/utility_work",
  "closure.closure": "closure/full_closure",
  "closure.closure.ramp": "closure/ramp_closure",
  "closure.closure.lane": "closure/lane_closure",
  "closure.closure.bridge": "closure/bridge_closure",
  "closure.closure.seasonal": "closure/seasonal_closure",
  "restriction.dimension": "restriction/weight",
  "restriction.dimension.height": "restriction/height",
  "restriction.dimension.width": "restriction/width",
  "restriction.dimension.length": "restriction/length",
  "restriction.access": null,
  "restriction.access.hazmat": "restriction/hazmat",
  "restriction.speed": null,
  "restriction.seasonal_load": "restriction/weight",
  "winter_operation.chain_control": "restriction/chain_control",
  "weather_condition.weather": "weather",
  "weather_condition.weather.ice": "weather/ice",
  "weather_condition.weather.snow": "weather/snow",
  "weather_condition.weather.high_wind": "weather/high_wind",
  "weather_condition.weather.fog": "weather/fog",
  "road_condition.surface": "road_condition",
  "road_condition.surface.icy": "road_condition/icy",
  "road_condition.surface.snow_covered": "road_condition/snow_covered",
  "road_condition.surface.wet": "road_condition/wet",
  "road_condition.surface.slush": "road_condition/slush",
  "road_condition.surface.dry": "road_condition/dry",
  "road_condition.driving_condition": "road_condition",
  "road_hazard.hazard": "hazard",
  "road_hazard.hazard.avalanche_risk": "weather/avalanche",
  "road_hazard.hazard.flooding": "weather/flooding",
  "public_event.event": "special_event",
  "public_event.event.sporting": "special_event/sporting",
  "public_event.event.parade": "special_event/parade",
  "public_event.event.concert": "special_event/concert",
  "authority.operation": "incident/police_activity",
  "equipment_fault.fault": "advisory",
  "security.incident": "advisory",
  "pass_status.pass": null,
  "congestion.congestion": null,
  "other.other": "advisory",
};

/** The `cause` vocabulary → GTFS-Realtime `Alert.Cause`. */
export const GTFS_RT_CAUSE_VALUES: Readonly<Record<string, string>> = {
  accident: "ACCIDENT",
  breakdown: "OTHER_CAUSE",
  debris: "OTHER_CAUSE",
  spill: "OTHER_CAUSE",
  fire: "OTHER_CAUSE",
  police_activity: "POLICE_ACTIVITY",
  animal: "OTHER_CAUSE",
  congestion: "OTHER_CAUSE",
  hazard: "OTHER_CAUSE",
  weather: "WEATHER",
  roadworks: "CONSTRUCTION",
  maintenance: "MAINTENANCE",
  construction: "CONSTRUCTION",
  public_event: "OTHER_CAUSE",
  security: "OTHER_CAUSE",
  infrastructure_failure: "TECHNICAL_PROBLEM",
  equipment_failure: "TECHNICAL_PROBLEM",
  flooding: "WEATHER",
  landslide: "WEATHER",
  avalanche: "WEATHER",
  wildfire: "WEATHER",
  strike: "STRIKE",
  demonstration: "DEMONSTRATION",
  medical_emergency: "MEDICAL_EMERGENCY",
  obstruction: "OTHER_CAUSE",
  abnormal_load: "OTHER_CAUSE",
  military: "OTHER_CAUSE",
  customs: "OTHER_CAUSE",
  unknown: "UNKNOWN_CAUSE",
  other: "OTHER_CAUSE",
};

/**
 * Roads classification → the DATEX II v3 record an emitter writes for it,
 * `Class` or `Class:discriminator`. DATEX is also a parsed vocabulary, where
 * many record codes read as one classification; reversing that index would
 * pick whichever code came first, so the emitter's choice lives here. Every
 * code reads back as the same kind; `null` marks a type with no record of its
 * own, which the emitter tells through its effects' records alone.
 */
export const DATEX2_RECORDS: Readonly<Record<string, string | null>> = {
  "incident.accident": "Accident",
  "incident.breakdown": "VehicleObstruction",
  "incident.vehicle_hazard": "VehicleObstruction",
  "incident.obstruction": "GeneralObstruction",
  "incident.obstruction.animal": "AnimalPresenceObstruction",
  "incident.obstruction.infrastructure_damage": "InfrastructureDamageObstruction",
  "incident.fire": "GeneralObstruction",
  "incident.fire.vehicle_fire": "VehicleObstruction:vehicleOnFire",
  "roadworks.works": "MaintenanceWorks",
  "roadworks.works.construction": "ConstructionWorks",
  "closure.closure": "RoadOrCarriagewayOrLaneManagement:roadClosed",
  "closure.closure.carriageway": "RoadOrCarriagewayOrLaneManagement:carriagewayClosures",
  "closure.closure.lane": "RoadOrCarriagewayOrLaneManagement:laneClosures",
  "closure.closure.ramp": "ReroutingManagement:doNotUseExit",
  "closure.closure.intermittent": "GeneralNetworkManagement:trafficHeld",
  "restriction.dimension": null,
  "restriction.access": null,
  "restriction.speed": "SpeedManagement",
  "restriction.speed.variable": "SpeedManagement:activeSpeedControlInOperation",
  "restriction.speed.advisory": "SpeedManagement:reduceYourSpeed",
  "restriction.seasonal_load": null,
  "weather_condition.weather": "PoorEnvironmentConditions",
  "road_condition.surface": "WeatherRelatedRoadConditions",
  "road_condition.driving_condition": "Conditions",
  "road_hazard.hazard": null,
  "road_hazard.hazard.flooding": "EnvironmentalObstruction:flooding",
  "road_hazard.hazard.avalanche_risk": "EnvironmentalObstruction:avalanches",
  "road_hazard.hazard.smoke": "EnvironmentalObstruction:smokeOrFumes",
  "public_event.event": "PublicEvent",
  "authority.operation": "AuthorityOperation",
  "equipment_fault.fault": "EquipmentOrSystemFault",
  "security.incident": "DisturbanceActivity",
  "winter_operation.chain_control": "WinterDrivingManagement",
  "pass_status.pass": null,
  "congestion.congestion": "AbnormalTraffic",
  "congestion.congestion.queuing": "AbnormalTraffic:queuingTraffic",
  "congestion.congestion.stationary": "AbnormalTraffic:stationaryTraffic",
  "congestion.congestion.slow": "AbnormalTraffic:slowTraffic",
  "congestion.congestion.heavy": "AbnormalTraffic:heavyTraffic",
  "other.other": "GeneralNetworkManagement",
};
