/**
 * DATEX II v3.7 energy-infrastructure vocabularies, verbatim from
 * `DATEXII_3_EnergyInfrastructure.xsd` (https://docs.datex2.eu/_static/data/v3.7/).
 * Its connector list is not OCPI's under another spelling: it writes the IEC
 * 60309 sockets as `iec60309x2single16`, and carries Tesla twice, once by
 * market (`teslaConnectorEurope`, `teslaConnectorAmerica`) and once by plug
 * (`teslaR`, `teslaS`).
 */
export const DATEX2_V3_ENERGY = {
  version: "3.7",
  energyInfrastructureSiteTypes: [
    "roofedStation",
    "inBuilding",
    "openSpace",
    "onstreet",
    "onCompanySite",
    "other",
    "_extended",
  ],
  serviceTypes: ["fullService", "selfService", "unattended", "_extended"],
  refillPointStatuses: [
    "available",
    "blocked",
    "charging",
    "faulted",
    "inoperative",
    "occupied",
    "outOfOrder",
    "outOfStock",
    "planned",
    "removed",
    "reserved",
    "unavailable",
    "unknown",
    "_extended",
  ],
  chargingPointUsageTypes: [
    "electricBoat",
    "electricBike",
    "electricalDevices",
    "electricMotorcycle",
    "electricVehicle",
    "lorryPowerConsumption",
    "motorhomeOrCaravanSupply",
    "overheadLineDrivenVehicles",
    "other",
    "_extended",
  ],
  chargingModes: [
    "mode1AC1p",
    "mode1AC3p",
    "mode2AC1p",
    "mode2AC3p",
    "mode3AC3p",
    "mode4DC",
    "legacyInductive",
    "ccs",
    "other",
    "unknown",
    "_extended",
  ],
  connectorTypes: [
    "chademo",
    "cee3",
    "cee5",
    "yazaki",
    "domestic",
    "domesticA",
    "domesticB",
    "domesticC",
    "domesticD",
    "domesticE",
    "domesticF",
    "domesticG",
    "domesticH",
    "domesticI",
    "domesticJ",
    "domesticK",
    "domesticL",
    "domesticM",
    "domesticN",
    "domesticO",
    "iec60309x2single16",
    "iec60309x2three16",
    "iec60309x2three32",
    "iec60309x2three64",
    "iec62196T1",
    "iec62196T1COMBO",
    "iec62196T2",
    "iec62196T2COMBO",
    "iec62196T3A",
    "iec62196T3C",
    "pantographBottomUp",
    "pantographTopDown",
    "teslaConnectorEurope",
    "teslaConnectorAmerica",
    "teslaR",
    "teslaS",
    "other",
    "_extended",
  ],
  connectorFormatTypes: ["cableMode2", "cableMode3", "otherCable", "socket", "_extended"],
  authenticationAndIdentificationMethods: [
    "activeRFIDChip",
    "apps",
    "calypso",
    "cashPayment",
    "creditCard",
    "debitCard",
    "mifareClassic",
    "mifareDesfire",
    "nfc",
    "overTheAir",
    "phoneDialog",
    "phoneSMS",
    "pinpad",
    "plc",
    "prepaidCard",
    "rfid",
    "website",
    "unlimitedAccess",
    "noAccess",
    "_extended",
  ],
  electricEnergySourceTypes: [
    "biogas",
    "coal",
    "gas",
    "nuclear",
    "solar",
    "water",
    "wind",
    "generalGreen",
    "generalFossil",
    "other",
    "_extended",
  ],
  pricingPolicies: [
    "pricePerChargingTime",
    "pricePerDeliveryUnit",
    "contract",
    "flatRate",
    "unknown",
    "free",
    "other",
    "_extended",
  ],
  deliveryUnits: [
    "litre",
    "kWh",
    "kg",
    "m3",
    "imperialGallon",
    "usGallon",
    "gasGallonEquivalent",
    "_extended",
  ],
} as const;
