/**
 * OCPI 2.2.1 vocabularies, verbatim from the specification
 * (https://github.com/ocpi/ocpi, release-2.2.1-bugfixes: `mod_locations` and
 * `mod_tariffs`). Values are case-sensitive on the wire, and the casing is
 * not uniform: `OUTOFORDER` is one word where every other multi-word value is
 * split, and the IEC 60309 connectors mix cases inside one value.
 */
export const OCPI_2_2_1 = {
  version: "2.2.1",
  evseStatuses: [
    "AVAILABLE",
    "BLOCKED",
    "CHARGING",
    "INOPERATIVE",
    "OUTOFORDER",
    "PLANNED",
    "REMOVED",
    "RESERVED",
    "UNKNOWN",
  ],
  capabilities: [
    "CHARGING_PROFILE_CAPABLE",
    "CHARGING_PREFERENCES_CAPABLE",
    "CHIP_CARD_SUPPORT",
    "CONTACTLESS_CARD_SUPPORT",
    "CREDIT_CARD_PAYABLE",
    "DEBIT_CARD_PAYABLE",
    "PED_TERMINAL",
    "REMOTE_START_STOP_CAPABLE",
    "RESERVABLE",
    "RFID_READER",
    "START_SESSION_CONNECTOR_REQUIRED",
    "TOKEN_GROUP_CAPABLE",
    "UNLOCK_CAPABLE",
  ],
  connectorTypes: [
    "CHADEMO",
    "CHAOJI",
    "DOMESTIC_A",
    "DOMESTIC_B",
    "DOMESTIC_C",
    "DOMESTIC_D",
    "DOMESTIC_E",
    "DOMESTIC_F",
    "DOMESTIC_G",
    "DOMESTIC_H",
    "DOMESTIC_I",
    "DOMESTIC_J",
    "DOMESTIC_K",
    "DOMESTIC_L",
    "DOMESTIC_M",
    "DOMESTIC_N",
    "DOMESTIC_O",
    "GBT_AC",
    "GBT_DC",
    "IEC_60309_2_single_16",
    "IEC_60309_2_three_16",
    "IEC_60309_2_three_32",
    "IEC_60309_2_three_64",
    "IEC_62196_T1",
    "IEC_62196_T1_COMBO",
    "IEC_62196_T2",
    "IEC_62196_T2_COMBO",
    "IEC_62196_T3A",
    "IEC_62196_T3C",
    "NEMA_5_20",
    "NEMA_6_30",
    "NEMA_6_50",
    "NEMA_10_30",
    "NEMA_10_50",
    "NEMA_14_30",
    "NEMA_14_50",
    "PANTOGRAPH_BOTTOM_UP",
    "PANTOGRAPH_TOP_DOWN",
    "TESLA_R",
    "TESLA_S",
  ],
  connectorFormats: ["SOCKET", "CABLE"],
  powerTypes: ["AC_1_PHASE", "AC_2_PHASE", "AC_2_PHASE_SPLIT", "AC_3_PHASE", "DC"],
  facilities: [
    "HOTEL",
    "RESTAURANT",
    "CAFE",
    "MALL",
    "SUPERMARKET",
    "SPORT",
    "RECREATION_AREA",
    "NATURE",
    "MUSEUM",
    "BIKE_SHARING",
    "BUS_STOP",
    "TAXI_STAND",
    "TRAM_STOP",
    "METRO_STATION",
    "TRAIN_STATION",
    "AIRPORT",
    "PARKING_LOT",
    "CARPOOL_PARKING",
    "FUEL_STATION",
    "WIFI",
  ],
  parkingTypes: [
    "ALONG_MOTORWAY",
    "PARKING_GARAGE",
    "PARKING_LOT",
    "ON_DRIVEWAY",
    "ON_STREET",
    "UNDERGROUND_GARAGE",
  ],
  parkingRestrictions: ["EV_ONLY", "PLUGGED", "DISABLED", "CUSTOMERS", "MOTORCYCLES"],
  imageCategories: ["CHARGER", "ENTRANCE", "LOCATION", "NETWORK", "OPERATOR", "OTHER", "OWNER"],
  energySourceCategories: [
    "NUCLEAR",
    "GENERAL_FOSSIL",
    "COAL",
    "GAS",
    "GENERAL_GREEN",
    "SOLAR",
    "WIND",
    "WATER",
  ],
  environmentalImpactCategories: ["NUCLEAR_WASTE", "CARBON_DIOXIDE"],
  tariffTypes: ["AD_HOC_PAYMENT", "PROFILE_CHEAP", "PROFILE_FAST", "PROFILE_GREEN", "REGULAR"],
  tariffDimensionTypes: ["ENERGY", "FLAT", "PARKING_TIME", "TIME"],
  daysOfWeek: ["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY"],
  reservationRestrictionTypes: ["RESERVATION", "RESERVATION_EXPIRES"],
} as const;
