/**
 * DATEX II weather vocabularies, verbatim from the official schemas: 3.7
 * `DATEXII_3_Common.xsd` and `DATEXII_3_RoadTrafficData.xsd`
 * (https://docs.datex2.eu/_static/data/v3.7/) and 2.3 `DATEXIISchema_2_2_3.xsd`
 * (https://docs.datex2.eu/_static/data/v2.3/DATEXIISchema_2_2_3_0.zip).
 * `measuredValues` lists, per concrete WeatherData class, the paths of its
 * measured values below the class (a `…Value` element or an enumeration).
 */
export const DATEX2_V3_WEATHER = {
  version: "3.7",
  precipitationTypes: [
    "clearIce",
    "dew",
    "diamondDust",
    "drizzle",
    "freezingRain",
    "glaze",
    "hail",
    "hardRime",
    "hoarFrost",
    "iceCrystals",
    "icePellets",
    "liquidFreezing",
    "liquidNotFreezing",
    "noPrecipitation",
    "rain",
    "rime",
    "sleet",
    "smallHail",
    "snow",
    "snowGrains",
    "snowPellets",
    "softRime",
    "solid",
    "wetSnow",
    "whiteDev",
    "unknown",
    "_extended",
  ],
  roadConditionTypes: [
    "blackIce",
    "deepSnow",
    "dry",
    "freezingOfWetRoads",
    "freezingPavements",
    "freezingRain",
    "freshSnow",
    "glaze",
    "ice",
    "iceBuildUp",
    "iceWithWheelBarTracks",
    "icyPatches",
    "looseSnow",
    "moist",
    "normalWinterConditionsForPedestrians",
    "notDry",
    "packedSnow",
    "rime",
    "roadSurfaceMelting",
    "slippery",
    "slushOnRoad",
    "slushStrings",
    "snow",
    "snowDrifts",
    "snowOnPavement",
    "wetAndIcyRoad",
    "snowOnTheRoad",
    "wetIcyPavement",
    "streamingWater",
    "surfaceWater",
    "wet",
    "other",
    "_extended",
  ],
  measuredValues: {
    HumidityInformation: ["humidity/relativeHumidity"],
    PollutionInformation: ["pollution/pollutantType", "pollution/pollutantConcentration"],
    PrecipitationInformation: [
      "noPrecipitation",
      "precipitationDetail/precipitationType",
      "precipitationDetail/precipitationIntensityGrade",
      "precipitationDetail/precipitationIntensity",
      "precipitationDetail/depositionDepth",
    ],
    PressureInformation: ["pressure/pressureValue"],
    RoadSurfaceConditionInformation: [
      "weatherRelatedRoadConditionType",
      "roadSurfaceConditionMeasurements/temperatureBelowOrAboveRoadSurface/heightBelowOrAboveRoadSurface",
      "roadSurfaceConditionMeasurements/temperatureBelowOrAboveRoadSurface/temperatureBelowOrAboveRoadSurface",
      "roadSurfaceConditionMeasurements/roadSurfaceTemperature",
      "roadSurfaceConditionMeasurements/protectionTemperature",
      "roadSurfaceConditionMeasurements/deIcingApplicationRate",
      "roadSurfaceConditionMeasurements/deIcingConcentration",
      "roadSurfaceConditionMeasurements/friction",
      "roadSurfaceConditionMeasurements/depthOfSnow",
      "roadSurfaceConditionMeasurements/waterFilmThickness",
      "roadSurfaceConditionMeasurements/iceLayerThickness",
      "roadSurfaceConditionMeasurements/icePercentage",
    ],
    TemperatureInformation: [
      "temperature/airTemperature",
      "temperature/dewPointTemperature",
      "temperature/maximumTemperature",
      "temperature/minimumTemperature",
    ],
    VisibilityInformation: ["visibility/minimumVisibilityDistance"],
    WindInformation: [
      "wind/windMeasurementHeight",
      "wind/windSpeed",
      "wind/maximumWindSpeed",
      "wind/windDirectionBearing",
      "wind/maximumWindDirectionBearing",
      "wind/windDirectionCompass",
      "wind/maximumWindDirectionCompass",
    ],
  },
} as const;

export const DATEX2_V2_WEATHER = {
  version: "2.3",
  precipitationTypes: ["drizzle", "freezingRain", "hail", "rain", "sleet", "snow"],
  roadConditionTypes: [
    "blackIce",
    "deepSnow",
    "dry",
    "freezingOfWetRoads",
    "freezingPavements",
    "freezingRain",
    "freshSnow",
    "ice",
    "iceBuildUp",
    "iceWithWheelBarTracks",
    "icyPatches",
    "looseSnow",
    "normalWinterConditionsForPedestrians",
    "packedSnow",
    "roadSurfaceMelting",
    "slipperyRoad",
    "slushOnRoad",
    "slushStrings",
    "snowDrifts",
    "snowOnPavement",
    "snowOnTheRoad",
    "surfaceWater",
    "wet",
    "wetAndIcyRoad",
    "wetIcyPavement",
    "other",
  ],
  measuredValues: {
    HumidityInformation: ["humidity/relativeHumidity"],
    PollutionInformation: ["pollution/pollutantType", "pollution/pollutantConcentration"],
    PrecipitationInformation: [
      "noPrecipitation",
      "precipitationDetail/precipitationType",
      "precipitationDetail/precipitationIntensity",
      "precipitationDetail/depositionDepth",
    ],
    RoadSurfaceConditionInformation: [
      "weatherRelatedRoadConditionType",
      "roadSurfaceConditionMeasurements/roadSurfaceTemperature",
      "roadSurfaceConditionMeasurements/protectionTemperature",
      "roadSurfaceConditionMeasurements/deIcingApplicationRate",
      "roadSurfaceConditionMeasurements/deIcingConcentration",
      "roadSurfaceConditionMeasurements/depthOfSnow",
      "roadSurfaceConditionMeasurements/waterFilmThickness",
    ],
    TemperatureInformation: [
      "temperature/airTemperature",
      "temperature/dewPointTemperature",
      "temperature/maximumTemperature",
      "temperature/minimumTemperature",
    ],
    VisibilityInformation: ["visibility/minimumVisibilityDistance"],
    WindInformation: [
      "wind/windMeasurementHeight",
      "wind/windSpeed",
      "wind/maximumWindSpeed",
      "wind/windDirectionBearing",
      "wind/windDirectionCompass",
    ],
  },
} as const;
