import type { FeedAuth, FeedSourceBase, CredentialField } from "@openconditions/ingest-framework";

/** Every env var a feed names, via its auth kind + requiredEnv, in declaration order. */
export function feedEnvVars(feed: FeedSourceBase): string[] {
  const fromAuth = authEnvVars(feed.auth);
  return [...fromAuth, ...(feed.requiredEnv ?? [])].filter((v, i, a) => a.indexOf(v) === i);
}

function authEnvVars(auth: FeedAuth | undefined): string[] {
  if (!auth) return [];
  switch (auth.kind) {
    case "none":
      return [];
    case "query-key":
    case "header-key":
    case "bearer":
      return [auth.envVar];
    case "basic":
      return [auth.userEnvVar, auth.passEnvVar];
    case "oauth2-client-credentials":
      return [auth.clientIdEnvVar, auth.clientSecretEnvVar];
    case "mtls":
      return [auth.certEnvVar, auth.keyEnvVar, ...(auth.caEnvVar ? [auth.caEnvVar] : [])];
  }
}

const KEYED = (f: FeedSourceBase) => feedEnvVars(f).length > 0;

/**
 * The `.env.example` credential section (one commented block per keyed feed).
 *
 * Vars are deduped globally: a var is emitted once, under the first feed that
 * needs it. Feeds that share credentials (e.g. the Mobilithek region feeds'
 * shared mTLS cert/key) contribute no duplicate `VAR=` lines — `.env` parsers
 * are last-occurrence-wins, so duplicate blank lines would silently null out
 * a value an operator filled in under an earlier block.
 */
export function envExampleFor(feeds: FeedSourceBase[]): string {
  const seen = new Set<string>();
  const blocks: string[] = [];
  for (const f of feeds.filter(KEYED)) {
    const newVars = feedEnvVars(f).filter((v) => !seen.has(v));
    if (newVars.length === 0) continue;
    for (const v of newVars) seen.add(v);
    const lines = [`# ${f.name}`];
    const firstSetup = f.setup ? Object.values(f.setup)[0] : undefined;
    if (firstSetup?.url)
      lines.push(`# ${firstSetup.urlLabel ?? "Get credentials"}: ${firstSetup.url}`);
    if (firstSetup?.notes) lines.push(`# ${firstSetup.notes}`);
    for (const v of newVars) lines.push(`${v}=`);
    blocks.push(lines.join("\n"));
  }
  return blocks.join("\n\n") + "\n";
}

/**
 * Non-secret operational settings (not per-feed credentials). Layered feed
 * delivery is configured by these three env vars; they render as plain config
 * fields in the admin panel (no vault, no `*_FILE` path).
 */
const SERVICE_SETTINGS: Record<string, { title: string; description: string }> = {
  OPENCONDITIONS_FEEDS_DIR: {
    title: "Mounted feed overrides directory",
    description:
      "Directory of operator-mounted *.json5 feed override/add files; overrides baked-in feeds by id with no rebuild. Unset = no overrides.",
  },
  OPENCONDITIONS_FEEDS_REMOTE_URL: {
    title: "Remote feed bundle URL",
    description:
      "URL of a remote feed bundle (typically the public road-conditions-atlas) to pull descriptors from. Only used when remote-pull is enabled.",
  },
  OPENCONDITIONS_FEEDS_REMOTE_ENABLED: {
    title: "Enable remote feed-pull",
    description:
      'Set to "true" to opt the instance into remote-pull (default off). Every descriptor is schema-validated and every URL is egress-guarded; a snapshot is vendored so the instance survives the remote being down.',
  },
};

/** The `service.json` configSchema.properties object (admin-panel fields). */
export function configSchemaPropertiesFor(feeds: FeedSourceBase[]): Record<string, unknown> {
  const props: Record<string, unknown> = {};
  for (const [key, { title, description }] of Object.entries(SERVICE_SETTINGS)) {
    props[key] = { type: "string", title, description, "x-openmapx-secret": false };
  }
  for (const f of feeds.filter(KEYED)) {
    for (const v of feedEnvVars(f)) {
      const field: CredentialField | undefined = f.setup?.[v];
      const { title, description, ...setup } = field ?? { title: `${f.name} — ${v}` };
      props[v] = {
        type: "string",
        title: title ?? `${f.name} — ${v}`,
        ...(description ? { description } : {}),
        "x-openmapx-secret": true,
        ...(Object.keys(setup).length > 0 ? { "x-openmapx-setup": setup } : {}),
      };
    }
  }
  return props;
}

/** The `docs/road-feed-credentials.md` table. */
export function credentialsDocFor(feeds: FeedSourceBase[]): string {
  const header =
    "# Road feed credentials\n\n> Generated by `pnpm gen:credentials`. Do not edit by hand.\n\n| Feed | Env var(s) | License | How to get it |\n|---|---|---|---|\n";
  const rows = feeds.filter(KEYED).map((f) => {
    const vars = feedEnvVars(f)
      .map((v) => `\`${v}\``)
      .join(", ");
    const setup = f.setup ? Object.values(f.setup)[0] : undefined;
    const how = setup?.url ? `[${setup.urlLabel ?? "portal"}](${setup.url})` : (setup?.notes ?? "");
    return `| ${f.name} | ${vars} | ${f.license} | ${how} |`;
  });
  return header + rows.join("\n") + "\n";
}
