import type { FeedAuth, FeedSourceBase, CredentialField } from "@openconditions/ingest-framework";

/** Every env var a feed names, via its auth kind + requiredEnv, in declaration order. */
export function feedEnvVars(feed: FeedSourceBase): string[] {
  const fromAuth = authEnvVars(feed.auth);
  return [...fromAuth, ...(feed.requiredEnv ?? [])].filter((v, i, a) => a.indexOf(v) === i);
}

function authEnvVars(auth: FeedAuth | undefined): string[] {
  if (!auth) return [];
  switch (auth.kind) {
    case "none":
      return [];
    case "query-key":
    case "header-key":
    case "bearer":
      return [auth.envVar];
    case "basic":
      return [auth.userEnvVar, auth.passEnvVar];
    case "oauth2-client-credentials":
      return [auth.clientIdEnvVar, auth.clientSecretEnvVar];
    case "mtls":
      return [auth.certEnvVar, auth.keyEnvVar, ...(auth.caEnvVar ? [auth.caEnvVar] : [])];
  }
}

const KEYED = (f: FeedSourceBase) => feedEnvVars(f).length > 0;

/** The `.env.example` credential section (one commented block per keyed feed). */
export function envExampleFor(feeds: FeedSourceBase[]): string {
  const blocks = feeds.filter(KEYED).map((f) => {
    const lines = [`# ${f.name}`];
    const firstSetup = f.setup ? Object.values(f.setup)[0] : undefined;
    if (firstSetup?.url)
      lines.push(`# ${firstSetup.urlLabel ?? "Get credentials"}: ${firstSetup.url}`);
    if (firstSetup?.notes) lines.push(`# ${firstSetup.notes}`);
    for (const v of feedEnvVars(f)) lines.push(`${v}=`);
    return lines.join("\n");
  });
  return blocks.join("\n\n") + "\n";
}

/** The `service.json` configSchema.properties object (admin-panel credential fields). */
export function configSchemaPropertiesFor(feeds: FeedSourceBase[]): Record<string, unknown> {
  const props: Record<string, unknown> = {};
  for (const f of feeds.filter(KEYED)) {
    for (const v of feedEnvVars(f)) {
      const field: CredentialField | undefined = f.setup?.[v];
      const { title, description, ...setup } = field ?? { title: `${f.name} — ${v}` };
      props[v] = {
        type: "string",
        title: title ?? `${f.name} — ${v}`,
        ...(description ? { description } : {}),
        "x-openmapx-secret": true,
        ...(Object.keys(setup).length > 0 ? { "x-openmapx-setup": setup } : {}),
      };
    }
  }
  return props;
}

/** The `docs/road-feed-credentials.md` table. */
export function credentialsDocFor(feeds: FeedSourceBase[]): string {
  const header =
    "# Road feed credentials\n\n> Generated by `pnpm gen:credentials`. Do not edit by hand.\n\n| Feed | Env var(s) | License | How to get it |\n|---|---|---|---|\n";
  const rows = feeds.filter(KEYED).map((f) => {
    const vars = feedEnvVars(f)
      .map((v) => `\`${v}\``)
      .join(", ");
    const setup = f.setup ? Object.values(f.setup)[0] : undefined;
    const how = setup?.url ? `[${setup.urlLabel ?? "portal"}](${setup.url})` : (setup?.notes ?? "");
    return `| ${f.name} | ${vars} | ${f.license} | ${how} |`;
  });
  return header + rows.join("\n") + "\n";
}
