import { mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { type FeedDefinition, toCatalogFeed } from "@openconditions/ingest-framework";
import { describe, expect, it } from "vitest";
import { loadIngestCatalog } from "../../services/ingest/src/domains.js";
import { applyOrCheck } from "../gen-credentials.js";
import { type CredentialCatalog, configSchemaPropertiesFor } from "../lib/gen-credentials-lib.js";

const keyed: FeedDefinition = {
  operator: "keyed",
  product: "events",
  name: "Keyed",
  format: "geojson",
  tier: "authoritative",
  endpoints: { main: { url: "https://example.org/feed", cadenceSec: 300 } },
  credentials: { token: { title: "K token" } },
  auth: { kind: "bearer", credential: "token" },
  freshnessWindowSec: 900,
  license: "CC0-1.0",
  attribution: "t",
  privacyUrl: "https://example.org/privacy",
};

const catalog: CredentialCatalog = {
  feeds: [
    toCatalogFeed(keyed, {
      domain: "roads",
      region: "nl",
      file: "feeds/roads/nl.jsonc",
      maintainers: [],
    }),
  ],
  credentials: { groups: {} },
};

const loadedRepoCatalog = await loadIngestCatalog({});

function paths() {
  const d = mkdtempSync(join(tmpdir(), "gencred-"));
  const service = join(d, "service.json");
  writeFileSync(
    service,
    JSON.stringify(
      { id: "s", container: { image: "x" }, configSchema: { properties: {} } },
      null,
      2,
    ),
  );
  return { envExample: join(d, ".env.example"), serviceJson: service, doc: join(d, "creds.md") };
}

describe("gen-credentials", () => {
  it("credentials are generated from derived names", () => {
    const props = configSchemaPropertiesFor(loadedRepoCatalog);
    expect(props).toHaveProperty("MOBILITHEK_CERT");
    expect(props).toHaveProperty("DE_HH_AUTOBAHN_FLOW_SUBSCRIPTION_ID");
    expect(props).not.toHaveProperty("DE_HH_AUTOBAHNNORD_SUBSCRIPTION_ID");
  });

  it("write mode produces files; a re-check then reports no drift", () => {
    const p = paths();
    expect(applyOrCheck(catalog, p, true).drift).toEqual([]);
    expect(readFileSync(p.envExample, "utf8")).toContain("NL_KEYED_EVENTS_TOKEN=");
    // service.json got the property spliced in, other keys preserved:
    const svc = JSON.parse(readFileSync(p.serviceJson, "utf8"));
    expect(svc.container.image).toBe("x");
    expect(svc.configSchema.properties.NL_KEYED_EVENTS_TOKEN["x-openmapx-secret"]).toBe(true);
    expect(svc.configSchema.properties.SEGMENT_REGIONS).toMatchObject({
      type: "string",
      "x-openmapx-secret": false,
    });
    expect(readFileSync(p.doc, "utf8")).toContain("`NL_KEYED_EVENTS_TOKEN`");
    // check mode is now a no-op (no drift):
    expect(applyOrCheck(catalog, p, false).drift).toEqual([]);
  });

  it("check mode reports drift when a file is stale", () => {
    const p = paths();
    applyOrCheck(catalog, p, true);
    writeFileSync(p.envExample, "STALE\n");
    expect(applyOrCheck(catalog, p, false).drift.join()).toContain(".env.example");
  });

  it("write mode preserves the hand-authored service section in .env.example", () => {
    const p = paths();
    applyOrCheck(catalog, p, true);
    const written = readFileSync(p.envExample, "utf8");
    expect(written).toContain("DATABASE_URL=");
    expect(written).toContain("OPENCONDITIONS_MAX_FEED_BYTES=");
    expect(written).toContain("OPENCONDITIONS_FEEDS_REMOTE_ENABLED=");
    expect(written).toContain("NL_KEYED_EVENTS_TOKEN=");
    expect(written).toContain(
      "# === Feed credentials — generated by `pnpm gen:credentials`; do not edit below this line ===",
    );
  });
});
