import {
  type CatalogFeed,
  type FeedDefinition,
  type SharedCredentials,
  toCatalogFeed,
} from "@openconditions/ingest-framework";
import { describe, expect, it } from "vitest";
import {
  type CredentialCatalog,
  configSchemaPropertiesFor,
  credentialsDocFor,
  envExampleFor,
} from "../lib/gen-credentials-lib.js";

function feed(over: Partial<FeedDefinition>, region = "us"): CatalogFeed {
  const def: FeedDefinition = {
    operator: "test",
    product: "events",
    name: "Test",
    format: "geojson",
    tier: "authoritative",
    endpoints: { main: { url: "https://example.org/feed", cadenceSec: 300 } },
    freshnessWindowSec: 900,
    license: "CC0-1.0",
    attribution: "t",
    privacyUrl: "https://example.org/privacy",
    ...over,
  };
  return toCatalogFeed(def, { domain: "roads", region, file: "f.jsonc", maintainers: [] });
}

const ny = feed({
  subdivision: "ny",
  operator: "511",
  name: "511NY (New York)",
  license: "LicenseRef-511NY-DAA",
  credentials: {
    api_key: {
      title: "511NY API key (New York)",
      description: "Query key.",
      setup: { url: "https://511ny.org/my511/register", cost: "Free" },
    },
  },
  auth: { kind: "query-key", param: "key", credential: "api_key" },
});

const shared: SharedCredentials = {
  groups: {
    mobilithek: {
      cert: {
        title: "Mobilithek certificate",
        setup: { url: "https://mobilithek.info", urlLabel: "Mobilithek" },
      },
      key: { title: "Mobilithek key" },
    },
  },
};

const mobilithek = (subdivision: string) =>
  feed(
    {
      subdivision,
      operator: "mobilithek",
      name: `Mobilithek ${subdivision}`,
      endpoints: {
        main: { url: "https://m.example.org/${subscription_id}", cadenceSec: 300 },
      },
      credentials: { subscription_id: { title: `Subscription ${subdivision}` } },
      auth: { kind: "mtls", cert: "@mobilithek.cert", key: "@mobilithek.key" },
    },
    "de",
  );

const ofFeeds = (feeds: CatalogFeed[], credentials = shared): CredentialCatalog => ({
  feeds,
  credentials,
});

describe("gen-credentials-lib", () => {
  it("emits an .env.example block per keyed feed under its derived names", () => {
    const out = envExampleFor(ofFeeds([ny, feed({ operator: "open" })]));
    expect(out).toContain("# 511NY (New York) (us-ny-511-events)");
    expect(out).toContain("# Get credentials: https://511ny.org/my511/register");
    expect(out).toContain("US_NY_511_EVENTS_API_KEY=");
    expect(out).not.toContain("us-open-events");
  });

  it("emits a configSchema property matching the admin-panel contract", () => {
    const props = configSchemaPropertiesFor(ofFeeds([ny]));
    expect(props["US_NY_511_EVENTS_API_KEY"]).toEqual({
      type: "string",
      title: "511NY API key (New York)",
      description: "Query key.",
      "x-openmapx-secret": true,
      "x-openmapx-setup": { url: "https://511ny.org/my511/register", cost: "Free" },
    });
  });

  it("emits the layered feed-delivery settings as non-secret service settings", () => {
    const props = configSchemaPropertiesFor(ofFeeds([]));
    for (const key of [
      "OPENCONDITIONS_FEEDS_DIR",
      "OPENCONDITIONS_FEEDS_REMOTE_URL",
      "OPENCONDITIONS_FEEDS_REMOTE_ENABLED",
    ]) {
      expect(props[key]).toMatchObject({ type: "string", "x-openmapx-secret": false });
    }
  });

  it("emits a shared group's fields once, with the group's setup guide", () => {
    const catalog = ofFeeds([mobilithek("hh"), mobilithek("by")]);
    const out = envExampleFor(catalog);
    expect(out).toContain(
      "# Shared: mobilithek (de-hh-mobilithek-events, de-by-mobilithek-events)",
    );
    expect(out).toContain("# Mobilithek: https://mobilithek.info");
    expect(out.split("MOBILITHEK_CERT=").length - 1).toBe(1);
    expect(out.split("MOBILITHEK_KEY=").length - 1).toBe(1);
    expect(out).toContain("DE_HH_MOBILITHEK_EVENTS_SUBSCRIPTION_ID=");
    expect(out).toContain("DE_BY_MOBILITHEK_EVENTS_SUBSCRIPTION_ID=");

    const props = configSchemaPropertiesFor(catalog) as Record<string, Record<string, unknown>>;
    expect(props["MOBILITHEK_CERT"]).toMatchObject({
      title: "Mobilithek certificate",
      "x-openmapx-setup": { url: "https://mobilithek.info", urlLabel: "Mobilithek" },
    });
    expect(props["MOBILITHEK_KEY"]).not.toHaveProperty("x-openmapx-setup");
  });

  it("names a catalogue child's credentials after its parent", () => {
    const child: CatalogFeed = { ...ny, id: "us-ny-511-x-events", parentSourceId: ny.id };
    const props = configSchemaPropertiesFor(ofFeeds([child]));
    expect(Object.keys(props)).toContain("US_NY_511_EVENTS_API_KEY");
    expect(Object.keys(props)).not.toContain("US_NY_511_X_EVENTS_API_KEY");
  });

  it("documents each keyed feed with its env vars, licence and guide", () => {
    const doc = credentialsDocFor(ofFeeds([ny, mobilithek("hh"), mobilithek("by")]));
    expect(doc).toContain("> Generated by `pnpm gen:credentials`. Do not edit by hand.");
    expect(doc).toContain(
      "| 511NY (New York) | `us-ny-511-events` | `US_NY_511_EVENTS_API_KEY` | LicenseRef-511NY-DAA | [portal](https://511ny.org/my511/register) |",
    );
    expect(doc).toContain(
      "| `de-hh-mobilithek-events` | `MOBILITHEK_CERT`, `MOBILITHEK_KEY`, `DE_HH_MOBILITHEK_EVENTS_SUBSCRIPTION_ID` |",
    );
  });
});
