/**
 * `ParkingSiteStatusEnum` from the DATEX II v3.2 Parking schema
 * (https://docs.datex2.eu/_static/data/v3.2/DATEXII_3_Parking.xsd). Version 3.7
 * removed it, but NDW's live v3 status feed still publishes
 * `<parkingSiteStatus>`, so the values stay in the census apart from
 * `DATEX2_V3_PARKING`.
 */
export const DATEX2_V3_2_PARKING_SITE_STATUSES = [
  "spacesAvailable",
  "almostFull",
  "fullAtEntrance",
  "full",
  "unknown",
  "other",
] as const;

/**
 * DATEX II v3.7 parking vocabularies, verbatim from the official schemas
 * `DATEXII_3_Parking.xsd` and `DATEXII_3_Facilities.xsd`
 * (https://docs.datex2.eu/_static/data/v3.7/). The `_extended` value every
 * DATEX enumeration ends with is the schema's escape hatch for national
 * extensions, not a value a publisher means, and maps to nothing.
 */
export const DATEX2_V3_PARKING = {
  version: "3.7",
  parkingUsageScenarios: [
    "automatedParkingGarage",
    "carSharing",
    "delivery",
    "dropOff",
    "dropOffMechanical",
    "dropOffWithValet",
    "eventParking",
    "guidanceToAvailableSpaces",
    "kissAndRide",
    "liftshare",
    "motorwayParking",
    "nearbyMotorwayParking",
    "overnightParking",
    "parkAndCycle",
    "parkAndDrive",
    "parkAndRide",
    "parkAndWalk",
    "poiParking",
    "restArea",
    "serviceArea",
    "specialLocation",
    "staffGuidesToSpace",
    "truckParking",
    "vehicleLift",
    "zone",
    "other",
    "_extended",
  ],
  parkingOccupancyTrends: [
    "decreasing",
    "increasing",
    "stable",
    "increasingQuickly",
    "increasingSlowly",
    "decreasingQuickly",
    "decreasingSlowly",
    "unknown",
    "other",
    "_extended",
  ],
  parkingVacantSpaces: [
    "noParkingSpacesAvailable",
    "expectNoSpacesAvailable",
    "onlyAFewSpacesAvailable",
    "lessThan10SpacesAvailable",
    "lessThan20SpacesAvailable",
    "lessThan30SpacesAvailable",
    "lessThan40SpacesAvailable",
    "lessThan50SpacesAvailable",
    "unknown",
    "other",
    "_extended",
  ],
  parkingPlaceStatuses: [
    "full",
    "fullAtEntrance",
    "spacesAvailable",
    "almostFull",
    "overcrowding",
    "overcrowdingLevel1",
    "overcrowdingLevel2",
    "noOvercrowding",
    "unknown",
    "other",
    "_extended",
  ],
  parkingOccupancies: [
    "expectCarParkToBeFull",
    "percentage10",
    "percentage20",
    "percentage30",
    "percentage40",
    "percentage50",
    "percentage60",
    "percentage70",
    "percentage80",
    "percentage90",
    "full",
    "unknown",
    "_extended",
  ],
  parkingSecurity: [
    "socialControl",
    "securityStaff",
    "externalSecurity",
    "cctv",
    "dog",
    "guard24hours",
    "lighting",
    "floodLight",
    "fences",
    "areaSeperatedFromSurroundings",
    "none",
    "unknown",
    "other",
    "_extended",
  ],
  parkingSupervisions: [
    "remote",
    "onSite",
    "controlCentreOnSite",
    "controlCentreOffSite",
    "patrol",
    "none",
    "unknown",
    "other",
    "_extended",
  ],
  layouts: ["layBy", "openSpace", "nested", "field", "building", "_extended"],
  structureTypes: ["onStreet", "offStreetSurface", "offStreetStructure", "_extended"],
  accessTypes: ["entryAndExit", "entryOnly", "exitOnly", "reversible", "_extended"],
  openingStatuses: [
    "open",
    "openWithServiceLimitation",
    "closed",
    "closedOnHoliday",
    "closedOnMaintenance",
    "temporarilyClosed",
    "statusUnknown",
    "other",
    "_extended",
  ],
  operationStatuses: [
    "inOperation",
    "limitedOperation",
    "notInOperation",
    "notInOperationAbnormal",
    "technicalDefect",
    "unknown",
    "_extended",
  ],
} as const;

/**
 * DATEX II v2.3 parking vocabularies, verbatim from `DATEXIISchema_2_2_3.xsd`
 * (https://docs.datex2.eu/_static/data/v2.3/DATEXIISchema_2_2_3_0.zip). The
 * v2 profile is what the Dutch and Luxembourgish parking feeds publish, and
 * it splits status differently from v3: one `ParkingSiteStatusEnum` instead
 * of a place status, an occupancy and an opening status.
 */
export const DATEX2_V2_PARKING = {
  version: "2.3",
  parkingSiteStatuses: [
    "spacesAvailable",
    "almostFull",
    "fullAtEntrance",
    "full",
    "unknown",
    "other",
  ],
  parkingVacantSpaces: [
    "noParkingSpacesAvailable",
    "expectNoSpacesAvailable",
    "onlyAFewSpacesAvailable",
    "lessThan10SpacesAvailable",
    "lessThan20SpacesAvailable",
    "lessThan30SpacesAvailable",
    "lessThan40SpacesAvailable",
    "lessThan50SpacesAvailable",
    "unknown",
    "other",
  ],
  parkingOccupancyTrends: [
    "decreasing",
    "increasing",
    "stable",
    "increasingQuickly",
    "increasingSlowly",
    "decreasingQuickly",
    "decreasingSlowly",
    "unknown",
    "other",
  ],
  parkingUsageScenarios: [
    "truckParking",
    "parkAndRide",
    "parkAndCycle",
    "parkAndWalk",
    "kissAndRide",
    "liftshare",
    "carSharing",
    "restArea",
    "serviceArea",
    "dropOffWithValet",
    "dropOffMechanical",
    "eventParking",
    "automaticParkingGuidance",
    "staffGuidesToSpace",
    "vehicleLift",
    "loadingBay",
    "dropOff",
    "overnightParking",
    "unknown",
    "other",
  ],
  urbanParkingSiteTypes: ["onStreetParking", "offStreetParking", "other"],
  interUrbanParkingSiteLocations: ["motorway", "nearbyMotorway", "layBy", "onStreet", "other"],
  parkingLayouts: [
    "multiStorey",
    "singleLevel",
    "underground",
    "undergroundAndMultistorey",
    "automatedParkingGarage",
    "openSpace",
    "covered",
    "nested",
    "field",
    "unknown",
    "other",
  ],
  parkingSecurity: [
    "socialControl",
    "securityStaff",
    "externalSecurity",
    "cctv",
    "dog",
    "guard24hours",
    "lighting",
    "floodLight",
    "fences",
    "areaSeperatedFromSurroundings",
    "none",
    "unknown",
    "other",
  ],
  parkingSupervisions: [
    "remote",
    "onSite",
    "controlCentreOnSite",
    "controlCentreOffSite",
    "patrol",
    "none",
    "unknown",
    "other",
  ],
  parkingSiteOvercrowdingStatuses: [
    "overcrowding",
    "noOvercrowding",
    "overcrowdingLevel1",
    "overcrowdingLevel2",
    "unknown",
    "other",
  ],
} as const;
