/**
 * The facility lists the amenity vocabulary is mapped from: DATEX II v2.3
 * `ServiceFacilityTypeEnum` and v3.7 `fac:FacilityTypeEnum`.
 */
export const DATEX2_FACILITIES = {
  version: "2.3+3.7",
  serviceFacilityTypes: [
    "hotel",
    "motel",
    "overnightAccommodation",
    "shop",
    "kiosk",
    "foodShopping",
    "cafe",
    "restaurant",
    "restaurantSelfService",
    "motorwayRestaurant",
    "motorwayRestaurantSmall",
    "sparePartsShopping",
    "petrolStation",
    "vehicleMaintenance",
    "tyreRepair",
    "truckRepair",
    "truckWash",
    "carWash",
    "pharmacy",
    "medicalFacility",
    "police",
    "touristInformation",
    "bikeSharing",
    "docstop",
    "laundry",
    "leisureActivities",
    "unknown",
    "other",
  ],
  facilityTypes: [
    "airport",
    "carPark",
    "carRentalStation",
    "electricChargingStation",
    "energyInfrastructureSite",
    "lorryParkingSite",
    "parkingSite",
    "petrolStation",
    "publicTransportDepot",
    "publicTransportHub",
    "shoppingCentre",
    "trainStation",
    "other",
    "_extended",
  ],
} as const;
