import { readFileSync, writeFileSync } from "node:fs";
import type { FeedSourceBase } from "@openconditions/ingest-framework";
import {
  envExampleFor,
  configSchemaPropertiesFor,
  credentialsDocFor,
} from "./lib/gen-credentials-lib.js";

export interface GenPaths {
  envExample: string;
  serviceJson: string;
  doc: string;
}

/** Splice generated configSchema.properties into service.json, preserving every other key. */
function nextServiceJson(current: string, feeds: FeedSourceBase[]): string {
  const svc = JSON.parse(current) as { configSchema?: { properties?: unknown } };
  svc.configSchema = { ...(svc.configSchema ?? {}), properties: configSchemaPropertiesFor(feeds) };
  return JSON.stringify(svc, null, 2) + "\n";
}

const ENV_MARKER =
  "# === Feed credentials — generated by `pnpm gen:credentials`; do not edit below this line ===";

const DEFAULT_ENV_PREAMBLE = `# OpenConditions ingest — environment configuration
#
# Copy to \`.env\` and fill in. Every road feed below is credential-gated: the
# scheduler skips a feed until all of its variables are set, so you only need the
# ones for the sources you want live. See docs/road-feed-credentials.md for how to
# obtain each key and any access conditions.

# --- Service ---------------------------------------------------------------

# PostgreSQL/PostGIS connection (REQUIRED — the service refuses to start without it)
DATABASE_URL=postgres://openconditions:openconditions@localhost:5432/openconditions

# HTTP server (optional; defaults shown)
PORT=4100
HOST=0.0.0.0

# Rate limiting (optional; defaults shown)
RATE_LIMIT_MAX=120
RATE_LIMIT_WINDOW_MS=60000

# Number of proxy hops to trust for client IPs (optional; default 1)
TRUST_PROXY_HOPS=1

# OpenLR map-match resolver service URL (optional). If unset, observations that
# carry only OpenLR (no coordinates) are dropped rather than resolved.
OPENLR_RESOLVER_URL=

# Egress guard caps applied to every feed fetch (optional; defaults shown)
OPENCONDITIONS_MAX_FEED_BYTES=268435456
OPENCONDITIONS_FETCH_TIMEOUT_MS=60000
OPENCONDITIONS_MAX_REDIRECTS=5

${ENV_MARKER}`;

/** Splice the generated credential blocks below the marker into `.env.example`, preserving the hand-authored preamble above it (or seeding the default preamble if the marker is missing). */
export function nextEnvExample(current: string, feeds: FeedSourceBase[]): string {
  const idx = current.indexOf(ENV_MARKER);
  const preamble = idx >= 0 ? current.slice(0, idx + ENV_MARKER.length) : DEFAULT_ENV_PREAMBLE;
  return `${preamble}\n\n${envExampleFor(feeds)}`;
}

/** In --write mode, writes the three artifacts. In check mode, compares and collects drift. */
export function applyOrCheck(
  feeds: FeedSourceBase[],
  paths: GenPaths,
  write: boolean
): { drift: string[] } {
  const targets: [string, string][] = [
    [paths.envExample, nextEnvExample(safeRead(paths.envExample), feeds)],
    [paths.serviceJson, nextServiceJson(readFileSync(paths.serviceJson, "utf8"), feeds)],
    [paths.doc, credentialsDocFor(feeds)],
  ];
  const drift: string[] = [];
  for (const [file, next] of targets) {
    const before = safeRead(file);
    if (before === next) continue;
    if (write) writeFileSync(file, next);
    else drift.push(file);
  }
  return { drift };
}

function safeRead(file: string): string {
  try {
    return readFileSync(file, "utf8");
  } catch {
    return "";
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const { FEED_SOURCES } = await import("@openconditions/roads");
  const paths: GenPaths = {
    envExample: new URL("../.env.example", import.meta.url).pathname,
    serviceJson: new URL("../services/ingest/service.json", import.meta.url).pathname,
    doc: new URL("../docs/road-feed-credentials.md", import.meta.url).pathname,
  };
  const write = process.argv.includes("--write");
  const { drift } = applyOrCheck(FEED_SOURCES as unknown as FeedSourceBase[], paths, write);
  if (!write && drift.length > 0) {
    console.error(
      `✗ Credential metadata is out of sync:\n  ${drift.join("\n  ")}\n\nFix with:  pnpm gen:credentials --write`
    );
    process.exit(1);
  }
  if (write) console.info("✓ credential metadata regenerated");
}
