import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { loadIngestCatalog } from "../services/ingest/src/domains.js";
import { SETTING_READERS } from "../services/ingest/src/pipeline/osm-import.js";
import {
  type CredentialCatalog,
  configSchemaPropertiesFor,
  credentialsDocFor,
  envExampleFor,
} from "./lib/gen-credentials-lib.js";

export interface GenPaths {
  envExample: string;
  serviceJson: string;
  doc: string;
}

interface ServiceJson {
  id: string;
  container?: { environment?: Record<string, string> };
  configSchema?: { type?: "object"; properties?: unknown };
}

/**
 * Write the configSchema (an object of the service's own fields and the
 * catalogue's) into service.json, preserving every other key.
 * `container.environment` is hand-written and left as it is, but may not name
 * a config field: OpenMapX resolves the field into the environment (or mounts
 * it as a secret file), and a hand-written entry would only hide that.
 */
function nextServiceJson(svc: ServiceJson, catalog: CredentialCatalog): string {
  const properties = configSchemaPropertiesFor(catalog);
  for (const key of Object.keys(svc.container?.environment ?? {})) {
    if (properties[key] !== undefined) {
      throw new Error(
        `container.environment ${key} is a config field: remove the entry; OpenMapX sets it from the field`,
      );
    }
  }
  const next = {
    ...svc,
    configSchema: { type: "object", ...(svc.configSchema ?? {}), properties },
  };
  return `${JSON.stringify(next, null, 2)}\n`;
}

const ENV_MARKER =
  "# === Feed credentials — generated by `pnpm gen:credentials`; do not edit below this line ===";

const DEFAULT_ENV_PREAMBLE = `# OpenConditions ingest — environment configuration
#
# Copy to \`.env\` and fill in. Every feed below is credential-gated: the
# scheduler skips a feed until all of its variables are set, so you only need the
# ones for the sources you want live. See docs/feed-credentials.md for how to
# obtain each key and any access conditions.

# --- Service ---------------------------------------------------------------

# PostgreSQL/PostGIS connection (REQUIRED — the service refuses to start without it)
DATABASE_URL=postgres://openconditions:openconditions@localhost:5432/openconditions

# HTTP server (optional; defaults shown)
PORT=4100
HOST=0.0.0.0

# Rate limiting (optional; defaults shown)
RATE_LIMIT_MAX=120
RATE_LIMIT_WINDOW_MS=60000

# Operator token (optional, at least 32 characters). A request with
# \`Authorization: Bearer <token>\` reads in the operator scope: restricted sources
# and licences that are not public included, no rate limit. Unset = public only.
OPENCONDITIONS_OPERATOR_TOKEN=

# How long a bbox read waits for the on-demand sources it fetches, in
# milliseconds (optional; default 3000). A fetch still running then goes on and
# lands for the next read; the response reports the source as \`deadline\`.
OPENCONDITIONS_ON_DEMAND_DEADLINE_MS=

# Immediate reverse-proxy address ranges to trust for client IPs (optional).
# Only one proxy hop is accepted. Defaults cover local and container networks.
TRUST_PROXY_CIDRS=loopback,linklocal,uniquelocal

# OpenLR map-match resolver service URL (optional). If unset, observations that
# carry only OpenLR (no coordinates) are dropped rather than resolved.
OPENLR_RESOLVER_URL=

# Road graph coverage: one JSON array used by import, binding and profiles.
# Unset/[] imports no regions. Configure explicitly before enabling route effects.
# See docs/graph-binding.md for the schema and a Germany motorway example.
SEGMENT_REGIONS=[]

# Egress guard caps applied to every feed fetch (optional; defaults shown)
OPENCONDITIONS_MAX_FEED_BYTES=268435456
OPENCONDITIONS_FETCH_TIMEOUT_MS=60000
OPENCONDITIONS_MAX_REDIRECTS=5

# Static archive (nightly GeoParquet published-view snapshot). The build writes a
# dated \`archive-<class>-YYYY-MM-DD.parquet\` per record class of the
# redistributable published view and points \`archive-<class>.parquet\` at it (see
# docs/archive.md). Local filesystem only — object-storage/S3 upload is operator
# infra, not wired here.
# Output directory (optional; default ./data/archive).
OPENCONDITIONS_ARCHIVE_DIR=
# Nights of dated files to keep (optional; default 30; 0 keeps every night).
OPENCONDITIONS_ARCHIVE_KEEP_NIGHTS=
# Cron for the nightly build (optional; default "30 3 * * *"; set "off" to disable).
ARCHIVE_CRON=

# Layered feed delivery (optional). Feeds load at boot from baked-in defaults +
# an operator-mounted directory + an optional (default-off) remote bundle,
# merged by feed id with precedence mounted > remote > baked-in.
#
# Directory laid out like the baked catalogue (<domain>/<region>.jsonc, optional
# credentials.jsonc) whose feeds add to or override baked-in ones by id, no
# rebuild. Unset = baked-in feeds only.
OPENCONDITIONS_FEEDS_DIR=
# URL of a remote feed bundle (e.g. a published atlas/<domain>.json). Only used
# when remote-pull is enabled below.
OPENCONDITIONS_FEEDS_REMOTE_URL=
# "true" opts into remote-pull (default off). The bundle is checked like the
# baked catalogue and URL-guarded; a snapshot is kept under the state dir
# (\${OPENCONDITIONS_STATE_DIR:-/data}/feeds) so the instance survives the remote
# being down.
OPENCONDITIONS_FEEDS_REMOTE_ENABLED=

${ENV_MARKER}`;

/** Splice the generated credential blocks below the marker into `.env.example`, preserving the hand-authored preamble above it (or seeding the default preamble if the marker is missing). */
export function nextEnvExample(current: string, catalog: CredentialCatalog): string {
  const idx = current.indexOf(ENV_MARKER);
  const preamble = idx >= 0 ? current.slice(0, idx + ENV_MARKER.length) : DEFAULT_ENV_PREAMBLE;
  return `${preamble}\n\n${envExampleFor(catalog)}`;
}

/**
 * In --write mode, writes the three artifacts. In check mode, compares and
 * collects drift. Throws, in either mode, on an environment entry naming an
 * instance setting.
 */
export function applyOrCheck(
  catalog: CredentialCatalog,
  paths: GenPaths,
  write: boolean,
): { drift: string[] } {
  const svc = JSON.parse(readFileSync(paths.serviceJson, "utf8")) as ServiceJson;
  const targets: [string, string][] = [
    [paths.envExample, nextEnvExample(safeRead(paths.envExample), catalog)],
    [paths.serviceJson, nextServiceJson(svc, catalog)],
    [paths.doc, credentialsDocFor(catalog, svc.id)],
  ];
  const drift: string[] = [];
  for (const [file, next] of targets) {
    const before = safeRead(file);
    if (before === next) continue;
    if (write) writeFileSync(file, next);
    else drift.push(file);
  }
  return { drift };
}

function safeRead(file: string): string {
  try {
    return readFileSync(file, "utf8");
  } catch {
    return "";
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  // The baked catalogue alone: what ships is documented, not an operator's mount.
  const catalog = {
    ...(await loadIngestCatalog({})),
    settingReaders: SETTING_READERS,
  };
  const paths: GenPaths = {
    envExample: fileURLToPath(new URL("../.env.example", import.meta.url)),
    serviceJson: fileURLToPath(new URL("../services/ingest/service.json", import.meta.url)),
    doc: fileURLToPath(new URL("../docs/feed-credentials.md", import.meta.url)),
  };
  const write = process.argv.includes("--write");
  const { drift } = applyOrCheck(catalog, paths, write);
  if (!write && drift.length > 0) {
    console.error(
      `✗ Credential metadata is out of sync:\n  ${drift.join("\n  ")}\n\nFix with:  pnpm gen:credentials`,
    );
    process.exit(1);
  }
  if (write) console.info("✓ credential metadata regenerated");
}
