import type { RoadFeed } from "../../feed-schema.js";
import { roadFeed } from "./road-feed.js";

type TestFeed = Partial<RoadFeed> &
  Pick<RoadFeed, "region" | "product" | "format" | "attribution" | "license">;

/**
 * The parse-relevant fields of the catalogue feeds the parser tests read
 * (region, format, attribution, licence, mappings), under the source ids their
 * golden files name. Parser tests own this copy, so a catalogue edit cannot
 * change a parser test silently.
 */
const TEST_FEEDS: Record<string, TestFeed> = {
  "ar-ba-cortes-events": {
    region: "ar",
    product: "events",
    format: "geojson",
    attribution: "Gobierno de la Ciudad de Buenos Aires",
    license: "LicenseRef-CC-BY-2.5-AR",
    licenseUrl: "https://data.buenosaires.gob.ar/",
    geojson: {
      defaultType: "road_closure",
      headlineField: "nombre",
      descriptionField: "descripcion",
    },
  },
  "at-asfinag-events": {
    region: "at",
    product: "events",
    format: "datex2",
    attribution: "ASFINAG",
    license: "CC-BY-4.0",
    licenseUrl: "https://www.mobilitydata.gv.at/en/data",
  },
  "au-nsw-livetraffic-events": {
    region: "au",
    product: "events",
    format: "geojson",
    attribution: "Transport for NSW",
    license: "CC-BY-4.0",
    licenseUrl: "https://opendata.transport.nsw.gov.au/dataset/live-traffic-hazards",
    geojson: {
      typeField: "mainCategory",
      typeMap: {
        Incident: "accident",
        "Road Work": "roadworks",
        Flooding: "road_hazard.hazard.flooding",
        Fire: "hazard",
        "Major Event": "public_event",
        Alpine: "weather",
      },
      defaultType: "other",
      headlineField: "headline",
      descriptionField: "otherAdvice",
    },
  },
  "au-qld-traffic-events": {
    region: "au",
    product: "events",
    format: "geojson",
    attribution: "State of Queensland (Department of Transport and Main Roads)",
    license: "CC-BY-4.0",
    licenseUrl: "https://www.qldtraffic.qld.gov.au/",
    geojson: {
      idField: "id",
      typeField: "event_type",
      typeMap: {
        Hazard: "hazard",
        Crash: "accident",
        Congestion: "congestion",
        Roadworks: "roadworks",
        "Special event": "public_event",
        Flooding: "road_hazard.hazard.flooding",
      },
      defaultType: "other",
      headlineField: "description",
      descriptionField: "information",
      roadField: "road_summary.road_name",
      severityField: "event_priority",
      severityMap: { "Red Alert": "critical", High: "high", Medium: "medium", Low: "low" },
      updatedField: "last_updated",
    },
  },
  "au-sa-trafficsa-events": {
    region: "au",
    product: "events",
    format: "geojson",
    attribution: "Department for Infrastructure and Transport (South Australia)",
    license: "CC-BY-4.0",
    licenseUrl: "https://data.sa.gov.au/data/dataset/roadworks-and-incidents-real-time-information",
    geojson: {
      idField: "ROADWORKS_AND_INCIDENTS_ID",
      typeField: "REC_TYPE",
      typeMap: {
        ROADWORKS: "roadworks",
        "24HR ROADWORKS": "roadworks",
        "EMERGENCY WATERWORKS": "roadworks",
        "SIGNAL FAULT": "equipment_fault.fault.traffic_signal",
        INCIDENT: "obstruction",
        COLLISION: "accident",
        CRASH: "accident",
        FLOODING: "road_hazard.hazard.flooding",
        EVENT: "public_event",
        "ROAD CLOSURE": "road_closure",
        HAZARD: "hazard",
      },
      defaultType: "other",
      headlineField: "DESCRIPTION",
      roadField: "ROAD_NO",
    },
  },
  "au-vic-vicroads-flow": {
    region: "au",
    product: "flow",
    format: "geojson-flow",
    attribution: "Department of Transport and Planning (Victoria)",
    license: "CC-BY-4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    flowMap: {
      idField: "id",
      speedField: "averageSpeed",
      statusField: "condition",
      statusMap: { Light: "freeFlow", Medium: "heavy", Heavy: "congested" },
      updatedField: "publishedTime",
    },
  },
  "au-vic-transportvic-planned-events": {
    region: "au",
    product: "events",
    format: "vic-disruptions",
    attribution: "Department of Transport and Planning (Victoria)",
    license: "CC-BY-4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
  },
  "au-vic-transportvic-unplanned-events": {
    region: "au",
    product: "events",
    format: "vic-disruptions",
    attribution: "Department of Transport and Planning (Victoria)",
    license: "CC-BY-4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
  },
  "be-brussels-events": {
    region: "be",
    product: "events",
    format: "geojson",
    timezone: "Europe/Brussels",
    attribution: "Bruxelles Mobilité / Brussel Mobiliteit",
    license: "CC0-1.0",
    licenseUrl: "https://data.mobility.brussels/",
    geojson: {
      idField: "fid",
      typeField: "datex_codes",
      typeMap: { RWK: "roadworks", EMR: "public_event", ACC: "accident", JAM: "congestion" },
      defaultType: "other",
      headlineField: "consequences_fr",
      roadField: "location_fr",
      severityField: "importance",
      severityMap: { "0": "low", "1": "low", "2": "medium", "3": "high", "4": "critical" },
      updatedField: "last_update",
    },
  },
  "be-flanders-events": {
    region: "be",
    product: "events",
    format: "datex2",
    attribution: "Verkeerscentrum Vlaanderen",
    license: "CC-BY-4.0",
    licenseUrl: "https://www.verkeerscentrum.be/",
  },
  "be-miv-flow": {
    region: "be",
    product: "flow",
    format: "miv",
    attribution: "Agentschap Wegen en Verkeer / Vlaams Verkeerscentrum",
    license: "CC-BY-4.0",
    licenseUrl:
      "https://www.vlaanderen.be/digitaal-vlaanderen/onze-diensten-en-platformen/open-data",
  },
  "ca-bc-drivebc-events": {
    region: "ca",
    product: "events",
    format: "open511",
    timezone: "America/Vancouver",
    attribution:
      "Contains information licensed under the Open Government Licence – British Columbia",
    license: "LicenseRef-OGL-BC",
    snapshot: { completeness: "complete", recordsPath: "events" },
  },
  "ca-on-511-events": {
    region: "ca",
    product: "events",
    format: "ibi511",
    attribution: "Contains information licensed under the Open Government Licence – Ontario",
    license: "LicenseRef-OGL-ON",
    licenseUrl: "https://www.ontario.ca/page/open-government-licence-ontario",
  },
  "ca-on-511-conditions": {
    region: "ca",
    product: "conditions",
    format: "ibi511-conditions",
    attribution: "Contains information licensed under the Open Government Licence – Ontario",
    license: "LicenseRef-OGL-ON",
    licenseUrl: "https://www.ontario.ca/page/open-government-licence-ontario",
    snapshot: { completeness: "complete", recordsPath: "$" },
  },
  "ca-qc-mtq-events": {
    region: "ca",
    product: "events",
    format: "geojson",
    timezone: "America/Toronto",
    attribution: "Ministère des Transports du Québec (MTQ)",
    license: "CC-BY-4.0",
    licenseUrl: "https://www.donneesquebec.ca/",
    geojson: {
      idField: "identifiant",
      defaultType: "roadworks",
      headlineField: "identificationDesTravaux",
      descriptionField: "descriptionFrancais",
      roadField: "routeAutoroute",
      updatedField: "miseAJour",
      validFromField: "debut",
      validToField: "fin",
    },
  },
  "ca-qc-mtq-warnings-events": {
    region: "ca",
    product: "events",
    format: "geojson",
    timezone: "America/Toronto",
    attribution: "Ministère des Transports du Québec (MTQ)",
    license: "CC-BY-4.0",
    licenseUrl: "https://www.donneesquebec.ca/",
    geojson: {
      idField: "identifiant",
      typeField: "entrave",
      typeMap: {
        Fermeture: "road_closure",
        "Fermeture de 1 voie sur 2": "lane_closure",
        "Circulation en alternance": "lane_closure",
        "Circulation à contresens": "contraflow",
        "Circulation interdite aux véhicules lourds": "restriction.access.truck_ban",
      },
      defaultType: "other",
      headlineField: "localisation",
      descriptionField: "cause",
      roadField: "numeroRoute",
      validFromField: "enVigueurDepuis",
    },
  },
  "de-autobahn-events": {
    region: "de",
    product: "events",
    format: "autobahn",
    attribution: "Quelle: Die Autobahn GmbH des Bundes",
    license: "DL-DE-BY-2.0",
  },
  "de-be-berlin-events": {
    region: "de",
    product: "events",
    format: "geojson",
    attribution: "Verkehrsinformationszentrale Berlin (VIZ)",
    license: "DL-DE-BY-2.0",
    licenseUrl: "https://daten.berlin.de/",
    geojson: {
      idField: "id",
      typeField: "subtype",
      typeMap: {
        Baustelle: "roadworks",
        Bauarbeiten: "roadworks",
        Sperrung: "road_closure",
        Störung: "obstruction",
      },
      defaultType: "other",
      headlineField: "content",
      roadField: "street",
      severityField: "severity",
      severityMap: {
        Vollsperrung: "high",
        Fahrtrichtungssperrung: "medium",
        "keine Sperrung": "low",
      },
      updatedField: "tstore",
    },
  },
  "de-bw-svzbw-events": {
    region: "de",
    product: "events",
    format: "datex2",
    attribution: "MobiData BW / Ministerium für Verkehr Baden-Württemberg (SVZ-BW)",
    license: "DL-DE-BY-2.0",
    licenseUrl: "https://www.mobidata-bw.de",
  },
  "de-by-autobahn-flow": {
    region: "de",
    product: "flow",
    format: "datex2-measured",
    attribution: "Quelle: Die Autobahn GmbH des Bundes",
    license: "LicenseRef-GeoNutzV",
    licenseUrl: "https://www.gesetze-im-internet.de/geonutzv/",
  },
  "de-hh-autobahn-flow": {
    region: "de",
    product: "flow",
    format: "datex2-measured",
    attribution: "Quelle: Die Autobahn GmbH des Bundes",
    license: "LicenseRef-GeoNutzV",
    licenseUrl: "https://www.gesetze-im-internet.de/geonutzv/",
  },
  "de-he-autobahn-flow": {
    region: "de",
    product: "flow",
    format: "datex2-measured",
    attribution: "Quelle: Die Autobahn GmbH des Bundes",
    license: "LicenseRef-GeoNutzV",
    licenseUrl: "https://www.gesetze-im-internet.de/geonutzv/",
  },
  "de-hh-polizei-events": {
    region: "de",
    product: "events",
    format: "geojson",
    attribution: "Freie und Hansestadt Hamburg, Polizei Hamburg",
    license: "DL-DE-BY-2.0",
    licenseUrl: "https://www.govdata.de/dl-de/by-2-0",
    geojson: {
      idField: "id",
      typeField: "art",
      typeMap: {
        Accident: "incident.accident",
        VehicleObstruction: "incident.breakdown",
        GeneralObstruction: "incident.obstruction",
        EnvironmentalObstruction: "incident.obstruction",
        InfrastructureDamageObstruction: "incident.obstruction.infrastructure_damage",
        AbnormalTraffic: "congestion.congestion",
        MaintenanceWorks: "roadworks.works.maintenance",
        ConstructionWorks: "roadworks.works.construction",
        PoorEnvironmentConditions: "weather_condition.weather",
        PublicEvent: "public_event.event",
        EquipmentOrSystemFault: "equipment_fault.fault",
        RoadOrCarriagewayOrLaneManagement: "lane_closure",
        ReroutingManagement: "detour",
        SpeedManagement: "speed_restriction",
      },
      descriptionField: "description",
    },
  },
  "de-nw-autobahn-flow": {
    region: "de",
    product: "flow",
    format: "datex2-elaborated",
    attribution: "Quelle: Die Autobahn GmbH des Bundes",
    license: "LicenseRef-GeoNutzV",
    licenseUrl: "https://www.gesetze-im-internet.de/geonutzv/",
  },
  "de-nw-autobahn-los-flow": {
    region: "de",
    product: "flow",
    format: "datex2-elaborated",
    attribution: "Quelle: Die Autobahn GmbH des Bundes",
    license: "LicenseRef-GeoNutzV",
    licenseUrl: "https://www.gesetze-im-internet.de/geonutzv/",
  },
  "de-nw-bonn-flow": {
    region: "de",
    product: "flow",
    format: "bonn",
    attribution: "Bundesstadt Bonn",
    license: "DL-DE-ZERO-2.0",
    licenseUrl: "https://www.govdata.de/dl-de/zero-2-0",
  },
  "de-nw-verkehr-events": {
    region: "de",
    product: "events",
    format: "datex2",
    attribution: "Landesverkehrszentrale NRW (Straßen.NRW)",
    license: "DL-DE-ZERO-2.0",
    licenseUrl: "https://www.govdata.de/dl-de/zero-2-0",
  },
  "dk-vejdirektoratet-events": {
    region: "dk",
    product: "events",
    format: "datex2",
    attribution: "Vejdirektoratet (Danish Road Directorate)",
    license: "CC-BY-4.0",
    licenseUrl: "https://nap.vd.dk/",
  },
  "ee-tarktee-events": {
    region: "ee",
    product: "events",
    format: "datex2",
    attribution: "Transpordiamet (Estonian Transport Administration)",
    license: "CC-BY-4.0",
    licenseUrl: "https://andmed.eesti.ee/information-holders/transpordiamet",
  },
  "es-bcn-ajuntament-flow": {
    region: "es",
    product: "flow",
    format: "bcn-trams",
    attribution: "Ajuntament de Barcelona",
    license: "CC-BY-4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
  },
  "es-dgt-events": {
    region: "es",
    product: "events",
    format: "datex2",
    attribution: "Dirección General de Tráfico (DGT)",
    license: "CC-BY-4.0",
    licenseUrl: "https://nap.dgt.es",
  },
  "es-madrid-flow": {
    region: "es",
    product: "flow",
    format: "informo",
    attribution: "Ayuntamiento de Madrid",
    license: "CC-BY-4.0",
    licenseUrl: "https://datos.madrid.es/egob/catalogo/aviso-legal",
  },
  "fi-digitraffic-events": {
    region: "fi",
    product: "events",
    format: "digitraffic",
    attribution: "Fintraffic / Digitraffic",
    license: "CC-BY-4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    snapshot: { completeness: "complete", recordsPath: "features" },
  },
  "fi-fintraffic-flow": {
    region: "fi",
    product: "flow",
    format: "fintraffic-tms",
    attribution: "Fintraffic / Digitraffic",
    license: "CC-BY-4.0",
    licenseUrl: "https://www.fintraffic.fi/en/fintraffic/open-data",
  },
  "fr-bordeauxmetropole-flow": {
    region: "fr",
    product: "flow",
    format: "geojson-flow",
    attribution: "Bordeaux Métropole",
    license: "etalab-2.0",
    licenseUrl: "https://www.etalab.gouv.fr/licence-ouverte-open-licence",
    flowMap: {
      idField: "ident",
      statusField: "etat",
      statusMap: {
        FLUIDE: "freeFlow",
        DENSE: "heavy",
        EMBOUTEILLE: "congested",
        INCONNU: "unknown",
      },
      updatedField: "mdate",
    },
  },
  "fr-dir-events": {
    region: "fr",
    product: "events",
    format: "datex2",
    attribution: "DIR / Bison Futé",
    license: "etalab-2.0",
    licenseUrl: "https://www.etalab.gouv.fr/licence-ouverte-open-licence",
    snapshot: {
      completeness: "complete",
      rootElement: "d2LogicalModel",
      publicationElement: "payloadPublication",
      publicationType: "SituationPublication",
      recordElement: "situationRecord",
    },
  },
  "fr-dir-flow": {
    region: "fr",
    product: "flow",
    format: "datex2-measured",
    attribution: "Ministère de la Transition écologique / DIR",
    license: "etalab-2.0",
    licenseUrl: "https://www.etalab.gouv.fr/licence-ouverte-open-licence",
  },
  "fr-rennesmetropole-flow": {
    region: "fr",
    product: "flow",
    format: "geojson-flow",
    attribution: "Rennes Métropole",
    license: "ODbL-1.0",
    licenseUrl: "https://opendatacommons.org/licenses/odbl/1-0/",
    flowMap: {
      idField: "predefinedlocationreference",
      speedField: "averagevehiclespeed",
      freeFlowField: "vitesse_maxi",
      statusField: "trafficstatus",
      updatedField: "datetime",
    },
  },
  "gb-nationalhighways-events": {
    region: "gb",
    product: "events",
    format: "datex2",
    attribution: "Contains National Highways data © Crown copyright and database right",
    license: "OGL-UK-3.0",
    licenseUrl: "https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/",
  },
  "hk-td-flow": {
    region: "hk",
    product: "flow",
    format: "hk-td",
    attribution: "Transport Department, HKSAR",
    license: "LicenseRef-HK-Gov-Open-Data",
    licenseUrl: "https://data.gov.hk/en/terms-and-conditions",
  },
  "hr-hc-roadworks-events": {
    region: "hr",
    product: "events",
    format: "datex2",
    attribution: "Hrvatske ceste",
    license: "LicenseRef-OD-HR",
    licenseUrl: "https://data.gov.hr/otvorena-dozvola",
  },
  "hr-hc-events": {
    region: "hr",
    product: "events",
    format: "datex2",
    attribution: "Hrvatske ceste",
    license: "LicenseRef-OD-HR",
    licenseUrl: "https://data.gov.hr/otvorena-dozvola",
  },
  "is-vegagerdin-conditions": {
    region: "is",
    product: "conditions",
    format: "geojson",
    attribution: "Vegagerðin (Icelandic Road and Coastal Administration)",
    license: "CC-BY-4.0",
    licenseUrl: "https://www.vegagerdin.is/",
    geojson: {
      lonField: "X",
      latField: "Y",
      typeField: "DESCRIPTION",
      typeMap: {
        Closed: "road_closure",
        "Road repairs": "roadworks",
        "Uneven road": "road_condition.surface.rough",
        "Flying gravel": "road_condition.surface.loose_chippings",
        "Animals on the road": "incident.obstruction.animal",
        "Holes in road": "incident.obstruction.pothole",
        "Total axle weight limit": "restriction.dimension.axle_load",
      },
      defaultType: "hazard",
      headlineField: "DESCRIPTION",
      updatedField: "CREATIONTIME",
    },
  },
  "is-vegagerdin-lines-conditions": {
    region: "is",
    product: "conditions",
    format: "geojson",
    attribution: "Vegagerðin (Icelandic Road and Coastal Administration)",
    license: "CC-BY-4.0",
    licenseUrl: "https://www.vegagerdin.is/",
    geojson: {
      idField: "IDBUTUR",
      startLonField: "STARTX",
      startLatField: "STARTY",
      endLonField: "ENDX",
      endLatField: "ENDY",
      typeField: "ROADCONDITION",
      typeMap: {
        Closed: "road_closure",
        Impassable: "road_closure",
        "Impassable because of snow or weather": "weather",
        "Road repairs": "roadworks",
        "Spots of ice": "road_condition.surface.icy",
        "Mountain vehicles": "dimension_restriction",
        "No winter services": "road_condition.driving_condition.no_winter_maintenance",
      },
      defaultType: "road_condition",
      filter: [{ field: "ROADCONDITION", exclude: ["Easily passable", "Not known"] }],
      headlineField: "ROADCONDITION",
      descriptionField: "ADDITIONALINFORMATION",
      roadField: "ROADNUMBER",
      updatedField: "CREATIONTIME",
    },
  },
  "it-turin-flow": {
    region: "it",
    product: "flow",
    format: "fdt",
    attribution: "5T / Città di Torino",
    license: "CC-BY-4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
  },
  "lu-cita-events": {
    region: "lu",
    product: "events",
    format: "datex2",
    attribution: "CITA (Luxembourg)",
    license: "CC0-1.0",
    licenseUrl: "https://data.public.lu/en/datasets/cita-evenements-trafic-en-datex-ii-v3-6/",
    snapshot: {
      completeness: "complete",
      rootElement: "d2LogicalModel",
      publicationElement: "payloadPublication",
      publicationType: "SituationPublication",
      recordElement: "situationRecord",
    },
  },
  "nl-ndw-events": {
    region: "nl",
    product: "events",
    format: "datex2",
    attribution: "NDW / Rijkswaterstaat",
    license: "CC0-1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    laneNumbering: "left_first",
    snapshot: {
      completeness: "complete",
      rootElement: "messageContainer",
      publicationElement: "payload",
      publicationType: "SituationPublication",
      recordElement: "situationRecord",
    },
  },
  "nl-ndw-flow": {
    region: "nl",
    product: "flow",
    format: "datex2-measured",
    attribution: "NDW / Rijkswaterstaat",
    license: "CC0-1.0",
    licenseUrl: "https://www.ndw.nu",
    laneNumbering: "left_first",
  },
  "no-vegvesen-events": {
    region: "no",
    product: "events",
    format: "datex2",
    attribution: "Statens vegvesen",
    license: "NLOD-2.0",
    licenseUrl: "https://data.norge.no/nlod/en/2.0",
  },
  "no-vegvesen-flow": {
    region: "no",
    product: "flow",
    format: "datex2-measured",
    attribution: "Statens vegvesen",
    license: "NLOD-2.0",
    licenseUrl: "https://data.norge.no/nlod/en/2.0",
  },
  "nz-nzta-events": {
    region: "nz",
    product: "events",
    format: "geojson",
    attribution: "NZ Transport Agency Waka Kotahi",
    license: "CC-BY-4.0",
    licenseUrl: "https://opendata-nzta.opendata.arcgis.com/",
    geojson: {
      idField: "eventId",
      typeField: "eventDescription",
      typeMap: {
        Crash: "accident",
        Breakdown: "broken_down_vehicle",
        Slip: "incident.obstruction.landslide",
        Maintenance: "roadworks.works.maintenance",
        "Pavement Repairs": "roadworks",
        "Bridge Repairs": "roadworks.works.bridge_work",
        Resurfacing: "roadworks.works.resurfacing",
        "Road Construction": "roadworks.works.construction",
        Services: "roadworks",
      },
      defaultType: "other",
      headlineField: "eventDescription",
      descriptionField: "eventComments",
      severityField: "impact",
      severityMap: { "Road Closed": "high", Delays: "medium", Caution: "low" },
      updatedField: "eventModified",
    },
  },
  "pl-gddkia-events": {
    region: "pl",
    product: "events",
    format: "gddkia",
    attribution: "GDDKiA",
    license: "CC0-1.0",
    licenseUrl: "https://dane.gov.pl/",
  },
  "se-trafikverket-events": {
    region: "se",
    product: "events",
    format: "datex2",
    attribution: "Trafikverket",
    license: "CC0-1.0",
    licenseUrl: "https://data.trafikverket.se/",
    posListLonLat: true,
  },
  "se-trafikverket-flow": {
    region: "se",
    product: "flow",
    format: "trafikverket-flow",
    attribution: "Trafikverket",
    license: "CC0-1.0",
    licenseUrl: "https://api.trafikinfo.trafikverket.se/",
  },
  "sg-lta-events": {
    region: "sg",
    product: "events",
    format: "lta",
    attribution: "Land Transport Authority (Singapore)",
    license: "LicenseRef-Singapore-ODL-1.0",
    licenseUrl: "https://datamall.lta.gov.sg/content/datamall/en/SingaporeOpenDataLicence.html",
  },
  "sg-lta-flow": {
    region: "sg",
    product: "flow",
    format: "lta-speedbands",
    attribution: "Land Transport Authority (Singapore)",
    license: "LicenseRef-Singapore-ODL-1.0",
    licenseUrl: "https://datamall.lta.gov.sg/content/datamall/en/SingaporeOpenDataLicence.html",
  },
  "si-nap-events": {
    region: "si",
    product: "events",
    format: "datex2",
    attribution: "DARS / DRSI (NAP Slovenia)",
    license: "CC-BY-SA-4.0",
    licenseUrl: "https://nap.si/",
  },
  "th-longdo-events": {
    region: "th",
    product: "events",
    format: "flatjson",
    timezone: "Asia/Bangkok",
    attribution: "Longdo Traffic / iTIC Foundation",
    license: "CC-BY-4.0",
    licenseUrl: "https://www.longdo.com/",
    geojson: {
      lonField: "longitude",
      latField: "latitude",
      idField: "eid",
      typeField: "type",
      typeMap: { "3": "accident" },
      defaultType: "other",
      headlineField: "title_en",
      descriptionField: "description_en",
      updatedField: "start",
    },
  },
  "us-ny-511-events": {
    region: "us",
    product: "events",
    format: "ibi511",
    attribution: "511NY / New York State DOT",
    license: "LicenseRef-511NY-DAA",
    licenseUrl: "https://511ny.org/help/24",
  },
  "us-nyc-dot-flow": {
    region: "us",
    product: "flow",
    format: "nyc-dot",
    attribution: "New York City Department of Transportation",
    license: "LicenseRef-NYC-Open-Data",
    licenseUrl: "https://www.nyc.gov/html/data/terms.html",
  },
  "us-oh-ohgo-flow": {
    region: "us",
    product: "flow",
    format: "ohgo",
    attribution: "Ohio Department of Transportation (OHGO)",
    license: "LicenseRef-US-Gov-Public-Domain",
    licenseUrl: "https://www.usa.gov/government-works",
  },
  "us-oh-ohgo-construction-events": {
    region: "us",
    product: "events",
    format: "ohgo-events",
    attribution: "Ohio Department of Transportation (OHGO)",
    license: "LicenseRef-US-Gov-Public-Domain",
    licenseUrl: "https://www.usa.gov/government-works",
  },
  "us-oh-ohgo-events": {
    region: "us",
    product: "events",
    format: "ohgo-events",
    attribution: "Ohio Department of Transportation (OHGO)",
    license: "LicenseRef-US-Gov-Public-Domain",
    licenseUrl: "https://www.usa.gov/government-works",
  },
  "us-wzdx-events": {
    region: "us",
    product: "events",
    format: "wzdx",
    attribution: "WZDx publishers",
    license: "NOASSERTION",
    terms: { note: "WZDx feed registry" },
  },
};

/** Whether the parser tests carry a feed of this id. */
export const hasTestFeed = (id: string): boolean => Object.hasOwn(TEST_FEEDS, id);

/** A parser test's feed by its source id, with `extra` over its fields. */
export function testFeed(id: string, extra: Partial<RoadFeed> = {}): RoadFeed {
  const feed = TEST_FEEDS[id];
  if (feed === undefined) throw new Error(`no test feed ${id}`);
  return roadFeed({ id, ...feed, ...extra });
}
