/** DATEX II 3.7 situation vocabularies, verbatim from https://docs.datex2.eu/_static/data/v3.7/DATEXII_3_Situation.xsd. */
export const DATEX2_V3 = {
  version: "3.7",
  recordClasses: [
    "AbnormalTraffic",
    "Accident",
    "AnimalPresenceObstruction",
    "AuthorityOperation",
    "Conditions",
    "ConstructionWorks",
    "DisturbanceActivity",
    "EnvironmentalObstruction",
    "EquipmentOrSystemFault",
    "GeneralInstructionOrMessageToRoadUsers",
    "GeneralNetworkManagement",
    "GeneralObstruction",
    "GenericSituationRecord",
    "InfrastructureDamageObstruction",
    "MaintenanceWorks",
    "NonWeatherRelatedRoadConditions",
    "PoorEnvironmentConditions",
    "PublicEvent",
    "ReroutingManagement",
    "RoadOperatorServiceDisruption",
    "RoadOrCarriagewayOrLaneManagement",
    "RoadsideAssistance",
    "ServiceDisruption",
    "SpeedManagement",
    "TransitInformation",
    "VehicleObstruction",
    "WeatherRelatedRoadConditions",
    "WinterDrivingManagement",
  ],
  discriminators: {
    AbnormalTraffic: {
      element: "abnormalTrafficType",
      values: [
        "stationaryTraffic",
        "queuingTraffic",
        "slowTraffic",
        "heavyTraffic",
        "unspecifiedAbnormalTraffic",
        "other",
        "_extended",
      ],
    },
    Accident: {
      element: "accidentType",
      values: [
        "accident",
        "accidentInvolvingHazardousMaterials",
        "accidentInvolvingHeavyLorries",
        "accidentInvolvingMassTransitVehicle",
        "accidentInvolvingPublicTransport",
        "accidentInvolvingRadioactiveMaterial",
        "accidentInvolvingTrain",
        "collision",
        "multipleVehicleAccident",
        "secondaryAccident",
        "seriousInjuryOrFatalAccident",
        "vehicleStuckUnderBridge",
        "other",
        "_extended",
      ],
    },
    AnimalPresenceObstruction: {
      element: "animalPresenceType",
      values: [
        "animalsOnTheRoad",
        "herdOfAnimalsOnTheRoad",
        "largeAnimalsOnTheRoad",
        "smallAnimalsOnTheRoad",
        "wildAnimalsOnTheRoad",
        "_extended",
      ],
    },
    AuthorityOperation: {
      element: "authorityOperationType",
      values: [
        "accidentInvestigationWork",
        "bombSquadInAction",
        "civilEmergency",
        "customsOperation",
        "juridicalReconstruction",
        "policeCheckPoint",
        "policeInvestigation",
        "roadOperatorCheckPoint",
        "snowChainOnBoardOrSnowTyresMountedCheck",
        "snowChainOrSnowTyresMountedCheck",
        "survey",
        "transportOfVip",
        "undefinedAuthorityActivity",
        "vehicleInspectionCheckPoint",
        "vehicleWeighing",
        "weighInMotion",
        "other",
        "_extended",
      ],
    },
    Conditions: {
      element: "drivingConditionType",
      values: [
        "impossible",
        "hazardous",
        "normal",
        "passableWithCare",
        "unknown",
        "veryHazardous",
        "winterConditions",
        "other",
        "_extended",
      ],
    },
    ConstructionWorks: {
      element: "constructionWorkType",
      values: [
        "blastingWork",
        "constructionWork",
        "demolitionWork",
        "roadImprovementOrUpgrading",
        "roadWideningWork",
        "_extended",
      ],
    },
    DisturbanceActivity: {
      element: "disturbanceActivityType",
      values: [
        "airRaid",
        "altercationOfVehicleOccupants",
        "assault",
        "assetDestruction",
        "attack",
        "attackOnVehicle",
        "blockadeOrBarrier",
        "bombAlert",
        "crowd",
        "demonstration",
        "evacuation",
        "filterBlockade",
        "goSlowOperation",
        "gunfireOnRoadway",
        "illVehicleOccupants",
        "march",
        "peopleThrowingObjectsOnTheRoad",
        "publicDisturbance",
        "radioactiveLeakAlert",
        "riot",
        "sabotage",
        "securityAlert",
        "securityIncident",
        "sightseersObstructingAccess",
        "strike",
        "terroristIncident",
        "theft",
        "toxicCloudAlert",
        "unspecifiedAlert",
        "other",
        "_extended",
      ],
    },
    EnvironmentalObstruction: {
      element: "environmentalObstructionType",
      values: [
        "avalanches",
        "earthquakeDamage",
        "fallenTrees",
        "fallingIce",
        "fallingLightIceOrSnow",
        "flashFloods",
        "flooding",
        "forestFire",
        "grassFire",
        "landslips",
        "mudSlide",
        "sewerOverflow",
        "rockfalls",
        "seriousFire",
        "smokeOrFumes",
        "stormDamage",
        "subsidence",
        "other",
        "_extended",
      ],
    },
    EquipmentOrSystemFault: {
      element: "equipmentOrSystemFaultType",
      values: [
        "notWorking",
        "outOfService",
        "workingIncorrectly",
        "workingIntermittently",
        "_extended",
      ],
    },
    GeneralInstructionOrMessageToRoadUsers: {
      element: "generalInstructionToRoadUsersType",
      values: [
        "allowEmergencyVehiclesToPass",
        "approachWithCare",
        "avoidTheArea",
        "closeAllWindowsTurnOffHeaterAndVents",
        "crossJunctionWithCare",
        "doNotAllowUnnecessaryGaps",
        "doNotLeaveYourVehicle",
        "doNotThrowOutAnyBurningObjects",
        "doNotUseNavigationSystems",
        "driveCarefully",
        "driveWithExtremeCaution",
        "flashYourLights",
        "followTheVehicleInFrontSmoothly",
        "increaseNormalFollowingDistance",
        "inEmergencyWaitForPatrolService",
        "keepYourDistance",
        "leaveYourVehicleProceedToNextSafePlace",
        "noNakedFlames",
        "noOvertaking",
        "noSmoking",
        "noStopping",
        "noUturns",
        "observeAmberAlert",
        "observeSignals",
        "observeSigns",
        "onlyTravelIfAbsolutelyNecessary",
        "overtakeWithCare",
        "pullOverToTheEdgeOfTheRoadway",
        "stopAtNextSafePlace",
        "stopAtNextServiceArea",
        "switchOffEngine",
        "switchOffMobilePhonesAndTwoWayRadios",
        "testYourBrakes",
        "useBusService",
        "useFogLights",
        "useHazardWarningLights",
        "useHeadlights",
        "useRailService",
        "useTramService",
        "useUndergroundService",
        "waitForEscortVehicle",
        "other",
        "_extended",
      ],
    },
    GeneralNetworkManagement: {
      element: "generalNetworkManagementType",
      values: [
        "bridgeSwingInOperation",
        "convoyService",
        "obstacleSignalling",
        "rampMeteringInOperation",
        "temporaryTrafficLights",
        "tollGatesOpen",
        "trafficBeingManuallyDirected",
        "trafficHeld",
        "other",
        "_extended",
      ],
    },
    GeneralObstruction: {
      element: "obstructionType",
      values: [
        "airCrash",
        "childrenOnRoadway",
        "clearanceWork",
        "craneOperating",
        "cyclistsOnRoadway",
        "debris",
        "explosion",
        "explosionHazard",
        "hazardsOnTheRoad",
        "incident",
        "industrialAccident",
        "objectOnTheRoad",
        "objectsFallingFromMovingVehicle",
        "obstructionOnTheRoad",
        "peopleOnRoadway",
        "railCrash",
        "rescueAndRecoveryWork",
        "severeFrostDamagedRoadway",
        "shedLoad",
        "snowAndIceDebris",
        "spillageOccurringFromMovingVehicle",
        "spillageOnTheRoad",
        "unprotectedAccidentArea",
        "other",
        "_extended",
      ],
    },
    InfrastructureDamageObstruction: {
      element: "infrastructureDamageType",
      values: [
        "burstPipe",
        "burstWaterMain",
        "collapsedSewer",
        "damagedBridge",
        "damagedCrashBarrier",
        "damagedFlyover",
        "damagedGallery",
        "damagedGantry",
        "damagedRoadSurface",
        "damagedTunnel",
        "damagedViaduct",
        "fallenPowerCables",
        "gasLeak",
        "weakBridge",
        "other",
        "_extended",
      ],
    },
    MaintenanceWorks: {
      element: "roadMaintenanceType",
      values: [
        "accidentRepairWork",
        "clearanceWork",
        "controlledAvalanche",
        "installationWork",
        "grassCuttingWork",
        "litterClearance",
        "maintenanceWork",
        "maintenancePeopleOnRoad",
        "overheadWorks",
        "repairWork",
        "resurfacingWork",
        "roadMarkingWork",
        "roadsideWork",
        "roadworksClearance",
        "roadworks",
        "rockFallPreventativeMaintenance",
        "saltingInProgress",
        "snowploughsInUse",
        "sweepingOfRoad",
        "treeAndVegetationCuttingWork",
        "other",
        "_extended",
      ],
    },
    NonWeatherRelatedRoadConditions: {
      element: "nonWeatherRelatedRoadConditionType",
      values: [
        "dieselOnRoad",
        "leavesOnRoad",
        "looseChippings",
        "looseSandOnRoad",
        "mudOnRoad",
        "oilOnRoad",
        "petrolOnRoad",
        "roadMarkingNotPresent",
        "roadSurfaceInPoorCondition",
        "slipperyRoad",
        "other",
        "_extended",
      ],
    },
    PoorEnvironmentConditions: {
      element: "poorEnvironmentType",
      values: [
        "badWeather",
        "blizzard",
        "blowingDust",
        "blowingSnow",
        "crosswinds",
        "damagingHail",
        "denseFog",
        "eclipse",
        "extremeCold",
        "extremeHeat",
        "fog",
        "freezingFog",
        "frost",
        "gales",
        "gustyWinds",
        "hail",
        "heavyFrost",
        "heavyRain",
        "heavySnowfall",
        "hurricaneForceWinds",
        "lowSunGlare",
        "moderateFog",
        "nearbyFire",
        "nearbyFlooding",
        "ozonePollution",
        "pollution",
        "patchyFog",
        "precipitationInTheArea",
        "rain",
        "rainChangingToSnow",
        "sandStorms",
        "severeExhaustPollution",
        "severeSmog",
        "showers",
        "sleet",
        "smogAlert",
        "smokeHazard",
        "snowChangingToRain",
        "snowfall",
        "sprayHazard",
        "stormForceWinds",
        "strongGustsOfWind",
        "strongWinds",
        "swarmsOfInsects",
        "temperatureFalling",
        "thunderstorms",
        "tornadoes",
        "veryStrongGustsOfWind",
        "visibilityReduced",
        "whiteOut",
        "winterStorm",
        "_extended",
      ],
    },
    PublicEvent: {
      element: "publicEventType",
      values: [
        "agriculturalShow",
        "airShow",
        "artEvent",
        "athleticsMeeting",
        "commercialEvent",
        "culturalEvent",
        "ballGame",
        "baseballGame",
        "basketballGame",
        "beerFestival",
        "bicycleRace",
        "boatRace",
        "boatShow",
        "boxingTournament",
        "bullFight",
        "ceremonialEvent",
        "concert",
        "cricketMatch",
        "exhibition",
        "fair",
        "festival",
        "filmFestival",
        "filmTVMaking",
        "fireworkDisplay",
        "flowerEvent",
        "foodFestival",
        "footballMatch",
        "funfair",
        "gardeningOrFlowerShow",
        "golfTournament",
        "hockeyGame",
        "horseRaceMeeting",
        "internationalSportsMeeting",
        "majorEvent",
        "marathon",
        "market",
        "match",
        "motorShow",
        "motorSportRaceMeeting",
        "openAirConcert",
        "parade",
        "procession",
        "raceMeeting",
        "rugbyMatch",
        "severalMajorEvents",
        "show",
        "showJumping",
        "soundAndLightShow",
        "sportsMeeting",
        "stateOccasion",
        "streetFestival",
        "tennisTournament",
        "theatricalEvent",
        "tournament",
        "tradeFair",
        "waterSportsMeeting",
        "wineFestival",
        "winterSportsMeeting",
        "unknown",
        "other",
        "_extended",
      ],
    },
    ReroutingManagement: {
      element: "reroutingManagementType",
      values: [
        "doNotFollowDiversionSigns",
        "doNotUseEntry",
        "doNotUseExit",
        "doNotUseIntersectionOrJunction",
        "followDiversionSigns",
        "followLocalDiversion",
        "followSpecialMarkers",
        "useEntry",
        "useExit",
        "useIntersectionOrJunction",
        "_extended",
      ],
    },
    RoadOperatorServiceDisruption: {
      element: "roadOperatorServiceDisruptionType",
      values: [
        "emergencyTelephoneNumberOutOfService",
        "informationServiceTelephoneNumberOutOfService",
        "noTrafficOfficerPatrolService",
        "_extended",
      ],
    },
    RoadOrCarriagewayOrLaneManagement: {
      element: "roadOrCarriagewayOrLaneManagementType",
      values: [
        "carPoolLaneInOperation",
        "carriagewayClosures",
        "clearALaneForEmergencyVehicles",
        "clearALaneForSnowploughsAndGrittingVehicles",
        "closedPermanentlyForTheWinter",
        "contraflow",
        "doNotUseSpecifiedLanesOrCarriageways",
        "hardShoulderRunningInOperation",
        "hardShoulderRunningNotInOperation",
        "heightRestrictionInOperation",
        "intermittentShortTermClosures",
        "keepToTheLeft",
        "keepToTheRight",
        "laneClosures",
        "lanesDeviated",
        "narrowLanes",
        "newRoadworksLayout",
        "overnightClosures",
        "roadCleared",
        "roadClosed",
        "rollingRoadBlock",
        "rushHourLaneInOperation",
        "singleAlternateLineTraffic",
        "tidalFlowLaneInOperation",
        "turnAroundInOperation",
        "useOfSpecifiedLanesOrCarriagewaysAllowed",
        "useSpecifiedLanesOrCarriageways",
        "vehicleStorageInOperation",
        "weightRestrictionInOperation",
        "other",
        "_extended",
      ],
    },
    RoadsideAssistance: {
      element: "roadsideAssistanceType",
      values: [
        "airAmbulance",
        "busPassengerAssistance",
        "emergencyServices",
        "firstAid",
        "foodDelivery",
        "helicopterRescue",
        "vehicleRepair",
        "vehicleRecovery",
        "other",
        "_extended",
      ],
    },
    ServiceDisruption: {
      element: "serviceDisruptionType",
      values: [
        "barClosed",
        "dieselShortage",
        "fuelShortage",
        "lpgShortage",
        "methaneShortage",
        "noDieselForHeavyVehicles",
        "noDieselForLightVehicles",
        "noParkingAvailability",
        "noPublicTelephones",
        "noToiletFacilities",
        "noVehicleRepairFacilities",
        "petrolShortage",
        "restAreaBusy",
        "restAreaClosed",
        "restAreaOvercrowdedDriveToAnotherRestArea",
        "serviceAreaBusy",
        "serviceAreaClosed",
        "serviceAreaFuelStationClosed",
        "serviceAreaOvercrowdedDriveToAnotherServiceArea",
        "serviceAreaRestaurantClosed",
        "someCommercialServicesClosed",
        "waterShortage",
        "_extended",
      ],
    },
    SpeedManagement: {
      element: "speedManagementType",
      values: [
        "activeSpeedControlInOperation",
        "doNotSlowdownUnnecessarily",
        "observeSpeedLimit",
        "policeSpeedChecksInOperation",
        "reduceYourSpeed",
        "speedRestrictionInOperation",
        "other",
        "_extended",
      ],
    },
    TransitInformation: {
      element: "transitServiceInformation",
      values: [
        "cancellations",
        "delayDueToBadWeather",
        "delayDueToRepairs",
        "delayedUntilFurtherNotice",
        "delaysDueToFlotsam",
        "departureOnSchedule",
        "ferryReplacedByIceRoad",
        "freeShuttleServiceOperating",
        "informationServiceNotAvailable",
        "irregularServiceDelays",
        "loadCapacityChanged",
        "restrictionsForLongerVehicles",
        "serviceDelays",
        "serviceDelaysOfUncertainDuration",
        "serviceFullyBooked",
        "serviceNotOperating",
        "serviceNotOperatingSubstituteServiceAvailable",
        "serviceSuspended",
        "serviceWithdrawn",
        "shuttleServiceOperating",
        "temporaryChangesToTimetables",
        "other",
        "_extended",
      ],
    },
    VehicleObstruction: {
      element: "vehicleObstructionType",
      values: [
        "abandonedVehicle",
        "abnormalLoad",
        "brokenDownVehicle",
        "convoy",
        "damagedVehicle",
        "dangerousSlowMovingVehicle",
        "emergencyVehicle",
        "highSpeedEmergencyVehicle",
        "longLoad",
        "highSpeedChase",
        "medicalEmergency",
        "militaryConvoy",
        "overheightVehicle",
        "prohibitedVehicleOnTheRoad",
        "recklessDriver",
        "slowVehicle",
        "specialPermitTransport",
        "trackedVehicle",
        "unlitVehicleOnTheRoad",
        "vehicleOnFire",
        "vehicleCarryingHazardousMaterials",
        "vehicleInDifficulty",
        "vehicleOnWrongCarriageway",
        "vehicleStuck",
        "vehicleWithOverheightLoad",
        "vehicleWithOverwideLoad",
        "winterMaintetanceVehicleInTransfer",
        "other",
        "_extended",
      ],
    },
    WeatherRelatedRoadConditions: {
      element: "weatherRelatedRoadConditionType",
      values: [
        "blackIce",
        "deepSnow",
        "dry",
        "freezingOfWetRoads",
        "freezingPavements",
        "freezingRain",
        "freshSnow",
        "glaze",
        "ice",
        "iceBuildUp",
        "iceWithWheelBarTracks",
        "icyPatches",
        "looseSnow",
        "moist",
        "normalWinterConditionsForPedestrians",
        "notDry",
        "packedSnow",
        "rime",
        "roadSurfaceMelting",
        "slippery",
        "slushOnRoad",
        "slushStrings",
        "snow",
        "snowDrifts",
        "snowOnPavement",
        "wetAndIcyRoad",
        "snowOnTheRoad",
        "wetIcyPavement",
        "streamingWater",
        "surfaceWater",
        "wet",
        "other",
        "_extended",
      ],
    },
    WinterDrivingManagement: {
      element: "winterEquipmentManagementType",
      values: [
        "doNotUseStudTyres",
        "useSnowChains",
        "useSnowChainsOrTyres",
        "useSnowTyres",
        "winterEquipmentOnBoardRequired",
        "other",
        "_extended",
      ],
    },
  },
  causeTypes: [
    "abnormalTraffic",
    "accident",
    "animalPresence",
    "authorityOperation",
    "constructionWork",
    "disturbance",
    "drivingConditions",
    "environmentalObstruction",
    "equipmentOrSystemFault",
    "infrastructureDamageObstruction",
    "instructionToRoadUsers",
    "networkManagement",
    "nonWeatherRelatedRoadConditions",
    "obstruction",
    "poorEnvironment",
    "publicEvent",
    "rerouting",
    "roadMaintenance",
    "roadOperatorServiceDisruption",
    "roadOrCarriagewayOrLaneManagement",
    "roadsideAssistance",
    "roadsideServiceDisruption",
    "speedManagement",
    "transitServiceDisruption",
    "vehicleObstruction",
    "weatherRelatedRoadConditions",
    "winterEquipmentManagement",
    "earlierEvent",
    "earlierIncident",
    "holidayTraffic",
    "problemsAtBorderPost",
    "problemsAtCustomPost",
    "problemsOnLocalRoads",
    "roadsideEvent",
    "rubberNecking",
    "technicalProblems",
    "vandalism",
    "other",
    "_extended",
  ],
  severities: ["highest", "high", "medium", "low", "lowest", "none", "unknown", "_extended"],
  probabilities: ["certain", "probable", "riskOf", "_extended"],
} as const;

/** DATEX II 2.3 situation vocabularies, verbatim from https://docs.datex2.eu/_static/data/v2.3/ (DATEXIISchema_2_2_3.xsd). */
export const DATEX2_V2 = {
  version: "2.3",
  recordClasses: [
    "AbnormalTraffic",
    "Accident",
    "AnimalPresenceObstruction",
    "AuthorityOperation",
    "CarParks",
    "Conditions",
    "ConstructionWorks",
    "DisturbanceActivity",
    "EnvironmentalObstruction",
    "EquipmentOrSystemFault",
    "GeneralInstructionOrMessageToRoadUsers",
    "GeneralNetworkManagement",
    "GeneralObstruction",
    "InfrastructureDamageObstruction",
    "MaintenanceWorks",
    "NonWeatherRelatedRoadConditions",
    "OperatorAction",
    "PoorEnvironmentConditions",
    "PublicEvent",
    "ReroutingManagement",
    "RoadOperatorServiceDisruption",
    "RoadOrCarriagewayOrLaneManagement",
    "RoadsideAssistance",
    "RoadsideServiceDisruption",
    "SignSetting",
    "SpeedManagement",
    "TransitInformation",
    "VehicleObstruction",
    "WeatherRelatedRoadConditions",
    "WinterDrivingManagement",
  ],
  discriminators: {
    AbnormalTraffic: {
      element: "abnormalTrafficType",
      values: [
        "stationaryTraffic",
        "queuingTraffic",
        "slowTraffic",
        "heavyTraffic",
        "unspecifiedAbnormalTraffic",
        "other",
      ],
    },
    Accident: {
      element: "accidentType",
      values: [
        "accident",
        "accidentInvolvingBicycles",
        "accidentInvolvingBuses",
        "accidentInvolvingHazardousMaterials",
        "accidentInvolvingHeavyLorries",
        "accidentInvolvingMassTransitVehicle",
        "accidentInvolvingMopeds",
        "accidentInvolvingMotorcycles",
        "accidentInvolvingRadioactiveMaterial",
        "accidentInvolvingTrain",
        "chemicalSpillageAccident",
        "collision",
        "collisionWithAnimal",
        "collisionWithObstruction",
        "collisionWithPerson",
        "earlierAccident",
        "fuelSpillageAccident",
        "headOnCollision",
        "headOnOrSideCollision",
        "jackknifedArticulatedLorry",
        "jackknifedCaravan",
        "jackknifedTrailer",
        "multipleVehicleCollision",
        "multivehicleAccident",
        "oilSpillageAccident",
        "overturnedHeavyLorry",
        "overturnedTrailer",
        "overturnedVehicle",
        "rearCollision",
        "secondaryAccident",
        "seriousAccident",
        "sideCollision",
        "vehicleOffRoad",
        "vehicleSpunAround",
        "other",
      ],
    },
    AnimalPresenceObstruction: {
      element: "animalPresenceType",
      values: ["animalsOnTheRoad", "herdOfAnimalsOnTheRoad", "largeAnimalsOnTheRoad"],
    },
    AuthorityOperation: {
      element: "authorityOperationType",
      values: [
        "accidentInvestigationWork",
        "bombSquadInAction",
        "civilEmergency",
        "customsOperation",
        "juridicalReconstruction",
        "policeCheckPoint",
        "policeInvestigation",
        "roadOperatorCheckPoint",
        "survey",
        "transportOfVip",
        "undefinedAuthorityActivity",
        "vehicleInspectionCheckPoint",
        "vehicleWeighing",
        "weighInMotion",
        "other",
      ],
    },
    Conditions: {
      element: "drivingConditionType",
      values: [
        "impossible",
        "hazardous",
        "normal",
        "passableWithCare",
        "unknown",
        "veryHazardous",
        "winterConditions",
        "other",
      ],
    },
    ConstructionWorks: {
      element: "constructionWorkType",
      values: [
        "blastingWork",
        "constructionWork",
        "demolitionWork",
        "roadImprovementOrUpgrading",
        "roadWideningWork",
      ],
    },
    DisturbanceActivity: {
      element: "disturbanceActivityType",
      values: [
        "airRaid",
        "altercationOfVehicleOccupants",
        "assault",
        "assetDestruction",
        "attack",
        "attackOnVehicle",
        "blockadeOrBarrier",
        "bombAlert",
        "crowd",
        "demonstration",
        "evacuation",
        "filterBlockade",
        "goSlowOperation",
        "gunfireOnRoadway",
        "illVehicleOccupants",
        "march",
        "publicDisturbance",
        "radioactiveLeakAlert",
        "riot",
        "sabotage",
        "securityAlert",
        "securityIncident",
        "sightseersObstructingAccess",
        "strike",
        "terroristIncident",
        "theft",
        "toxicCloudAlert",
        "unspecifiedAlert",
        "other",
      ],
    },
    EnvironmentalObstruction: {
      element: "environmentalObstructionType",
      values: [
        "avalanches",
        "earthquakeDamage",
        "fallenTrees",
        "fallingIce",
        "fallingLightIceOrSnow",
        "flashFloods",
        "flooding",
        "forestFire",
        "grassFire",
        "landslips",
        "mudSlide",
        "sewerOverflow",
        "rockfalls",
        "seriousFire",
        "smokeOrFumes",
        "stormDamage",
        "subsidence",
        "other",
      ],
    },
    EquipmentOrSystemFault: {
      element: "equipmentOrSystemFaultType",
      values: ["notWorking", "outOfService", "workingIncorrectly", "workingIntermittently"],
    },
    GeneralInstructionOrMessageToRoadUsers: {
      element: "generalInstructionToRoadUsersType",
      values: [
        "allowEmergencyVehiclesToPass",
        "approachWithCare",
        "avoidTheArea",
        "closeAllWindowsTurnOffHeaterAndVents",
        "crossJunctionWithCare",
        "doNotAllowUnnecessaryGaps",
        "doNotLeaveYourVehicle",
        "doNotThrowOutAnyBurningObjects",
        "doNotUseNavigationSystems",
        "driveCarefully",
        "driveWithExtremeCaution",
        "flashYourLights",
        "followTheVehicleInFrontSmoothly",
        "increaseNormalFollowingDistance",
        "inEmergencyWaitForPatrolService",
        "keepYourDistance",
        "leaveYourVehicleProceedToNextSafePlace",
        "noNakedFlames",
        "noOvertaking",
        "noSmoking",
        "noStopping",
        "noUturns",
        "observeAmberAlert",
        "observeSignals",
        "observeSigns",
        "onlyTravelIfAbsolutelyNecessary",
        "overtakeWithCare",
        "pullOverToTheEdgeOfTheRoadway",
        "stopAtNextSafePlace",
        "stopAtNextServiceArea",
        "switchOffEngine",
        "switchOffMobilePhonesAndTwoWayRadios",
        "testYourBrakes",
        "useBusService",
        "useFogLights",
        "useHazardWarningLights",
        "useHeadlights",
        "useRailService",
        "useTramService",
        "useUndergroundService",
        "waitForEscortVehicle",
        "other",
      ],
    },
    GeneralNetworkManagement: {
      element: "generalNetworkManagementType",
      values: [
        "bridgeSwingInOperation",
        "convoyService",
        "obstacleSignalling",
        "rampMeteringInOperation",
        "temporaryTrafficLights",
        "tollGatesOpen",
        "trafficBeingManuallyDirected",
        "trafficHeld",
        "other",
      ],
    },
    GeneralObstruction: {
      element: "obstructionType",
      values: [
        "airCrash",
        "childrenOnRoadway",
        "clearanceWork",
        "craneOperating",
        "cyclistsOnRoadway",
        "debris",
        "explosion",
        "explosionHazard",
        "hazardsOnTheRoad",
        "highSpeedChase",
        "houseFire",
        "incident",
        "industrialAccident",
        "objectOnTheRoad",
        "objectsFallingFromMovingVehicle",
        "obstructionOnTheRoad",
        "peopleOnRoadway",
        "railCrash",
        "recklessDriver",
        "rescueAndRecoveryWork",
        "severeFrostDamagedRoadway",
        "shedLoad",
        "snowAndIceDebris",
        "spillageOccurringFromMovingVehicle",
        "spillageOnTheRoad",
        "unprotectedAccidentArea",
        "other",
      ],
    },
    InfrastructureDamageObstruction: {
      element: "infrastructureDamageType",
      values: [
        "burstPipe",
        "burstWaterMain",
        "collapsedSewer",
        "damagedBridge",
        "damagedCrashBarrier",
        "damagedFlyover",
        "damagedGallery",
        "damagedGantry",
        "damagedRoadSurface",
        "damagedTunnel",
        "damagedViaduct",
        "fallenPowerCables",
        "gasLeak",
        "weakBridge",
        "other",
      ],
    },
    MaintenanceWorks: {
      element: "roadMaintenanceType",
      values: [
        "clearanceWork",
        "controlledAvalanche",
        "installationWork",
        "grassCuttingWork",
        "litterClearance",
        "maintenanceWork",
        "overheadWorks",
        "repairWork",
        "resurfacingWork",
        "roadMarkingWork",
        "roadsideWork",
        "roadworksClearance",
        "roadworks",
        "rockFallPreventativeMaintenance",
        "saltingInProgress",
        "snowploughsInUse",
        "sweepingOfRoad",
        "treeAndVegetationCuttingWork",
        "other",
      ],
    },
    NonWeatherRelatedRoadConditions: {
      element: "nonWeatherRelatedRoadConditionType",
      values: [
        "dieselOnRoad",
        "leavesOnRoad",
        "looseChippings",
        "looseSandOnRoad",
        "mudOnRoad",
        "oilOnRoad",
        "petrolOnRoad",
        "roadSurfaceInPoorCondition",
        "slipperyRoad",
        "other",
      ],
    },
    PoorEnvironmentConditions: {
      element: "poorEnvironmentType",
      values: [
        "badWeather",
        "blizzard",
        "blowingDust",
        "blowingSnow",
        "crosswinds",
        "damagingHail",
        "denseFog",
        "eclipse",
        "extremeCold",
        "extremeHeat",
        "fog",
        "freezingFog",
        "frost",
        "gales",
        "gustyWinds",
        "hail",
        "heavyFrost",
        "heavyRain",
        "heavySnowfall",
        "hurricaneForceWinds",
        "lowSunGlare",
        "moderateFog",
        "ozonePollution",
        "pollution",
        "patchyFog",
        "precipitationInTheArea",
        "rain",
        "rainChangingToSnow",
        "sandStorms",
        "severeExhaustPollution",
        "severeSmog",
        "showers",
        "sleet",
        "smogAlert",
        "smokeHazard",
        "snowChangingToRain",
        "snowfall",
        "sprayHazard",
        "stormForceWinds",
        "strongGustsOfWind",
        "strongWinds",
        "swarmsOfInsects",
        "temperatureFalling",
        "thunderstorms",
        "tornadoes",
        "veryStrongGustsOfWind",
        "visibilityReduced",
        "whiteOut",
        "winterStorm",
      ],
    },
    PublicEvent: {
      element: "publicEventType",
      values: [
        "agriculturalShow",
        "airShow",
        "athleticsMeeting",
        "commercialEvent",
        "culturalEvent",
        "ballGame",
        "baseballGame",
        "basketballGame",
        "bicycleRace",
        "boatRace",
        "boatShow",
        "boxingTournament",
        "bullFight",
        "ceremonialEvent",
        "concert",
        "cricketMatch",
        "exhibition",
        "fair",
        "festival",
        "filmTVMaking",
        "footballMatch",
        "funfair",
        "gardeningOrFlowerShow",
        "golfTournament",
        "hockeyGame",
        "horseRaceMeeting",
        "internationalSportsMeeting",
        "majorEvent",
        "marathon",
        "market",
        "match",
        "motorShow",
        "motorSportRaceMeeting",
        "parade",
        "procession",
        "raceMeeting",
        "rugbyMatch",
        "severalMajorEvents",
        "show",
        "showJumping",
        "sportsMeeting",
        "stateOccasion",
        "tennisTournament",
        "tournament",
        "tradeFair",
        "waterSportsMeeting",
        "winterSportsMeeting",
        "other",
      ],
    },
    ReroutingManagement: {
      element: "reroutingManagementType",
      values: [
        "doNotFollowDiversionSigns",
        "doNotUseEntry",
        "doNotUseExit",
        "doNotUseIntersectionOrJunction",
        "followDiversionSigns",
        "followLocalDiversion",
        "followSpecialMarkers",
        "useEntry",
        "useExit",
        "useIntersectionOrJunction",
      ],
    },
    RoadOperatorServiceDisruption: {
      element: "roadOperatorServiceDisruptionType",
      values: [
        "emergencyTelephoneNumberOutOfService",
        "informationServiceTelephoneNumberOutOfService",
        "noTrafficOfficerPatrolService",
      ],
    },
    RoadOrCarriagewayOrLaneManagement: {
      element: "roadOrCarriagewayOrLaneManagementType",
      values: [
        "carPoolLaneInOperation",
        "carriagewayClosures",
        "clearALaneForEmergencyVehicles",
        "clearALaneForSnowploughsAndGrittingVehicles",
        "closedPermanentlyForTheWinter",
        "contraflow",
        "doNotUseSpecifiedLanesOrCarriageways",
        "hardShoulderRunningInOperation",
        "heightRestrictionInOperation",
        "intermittentShortTermClosures",
        "keepToTheLeft",
        "keepToTheRight",
        "laneClosures",
        "lanesDeviated",
        "narrowLanes",
        "newRoadworksLayout",
        "overnightClosures",
        "roadCleared",
        "roadClosed",
        "rollingRoadBlock",
        "rushHourLaneInOperation",
        "singleAlternateLineTraffic",
        "tidalFlowLaneInOperation",
        "turnAroundInOperation",
        "useOfSpecifiedLanesOrCarriagewaysAllowed",
        "useSpecifiedLanesOrCarriageways",
        "vehicleStorageInOperation",
        "weightRestrictionInOperation",
        "other",
      ],
    },
    RoadsideAssistance: {
      element: "roadsideAssistanceType",
      values: [
        "airAmbulance",
        "busPassengerAssistance",
        "emergencyServices",
        "firstAid",
        "foodDelivery",
        "helicopterRescue",
        "vehicleRepair",
        "vehicleRecovery",
        "other",
      ],
    },
    SpeedManagement: {
      element: "speedManagementType",
      values: [
        "activeSpeedControlInOperation",
        "doNotSlowdownUnnecessarily",
        "observeSpeedLimit",
        "policeSpeedChecksInOperation",
        "reduceYourSpeed",
        "speedRestrictionInOperation",
        "other",
      ],
    },
    TransitInformation: {
      element: "transitServiceInformation",
      values: [
        "cancellations",
        "delayDueToBadWeather",
        "delayDueToRepairs",
        "delayedUntilFurtherNotice",
        "delaysDueToFlotsam",
        "departureOnSchedule",
        "ferryReplacedByIceRoad",
        "freeShuttleServiceOperating",
        "informationServiceNotAvailable",
        "irregularServiceDelays",
        "loadCapacityChanged",
        "restrictionsForLongerVehicles",
        "serviceDelays",
        "serviceDelaysOfUncertainDuration",
        "serviceFullyBooked",
        "serviceNotOperating",
        "serviceNotOperatingSubstituteServiceAvailable",
        "serviceSuspended",
        "serviceWithdrawn",
        "shuttleServiceOperating",
        "temporaryChangesToTimetables",
        "other",
      ],
    },
    VehicleObstruction: {
      element: "vehicleObstructionType",
      values: [
        "abandonedVehicle",
        "abnormalLoad",
        "brokenDownBus",
        "brokenDownHeavyLorry",
        "brokenDownVehicle",
        "convoy",
        "damagedVehicle",
        "dangerousSlowMovingVehicle",
        "emergencyVehicle",
        "highSpeedEmergencyVehicle",
        "longLoad",
        "militaryConvoy",
        "overheightVehicle",
        "prohibitedVehicleOnTheRoadway",
        "saltingOrGrittingVehicleInUse",
        "slowMovingMaintenanceVehicle",
        "slowVehicle",
        "snowplough",
        "trackLayingVehicle",
        "unlitVehicleOnTheRoad",
        "vehicleOnFire",
        "vehicleCarryingHazardousMaterials",
        "vehicleInDifficulty",
        "vehicleOnWrongCarriageway",
        "vehicleStuck",
        "vehicleStuckUnderBridge",
        "vehicleWithOverheightLoad",
        "vehicleWithOverwideLoad",
        "other",
      ],
    },
    WeatherRelatedRoadConditions: {
      element: "weatherRelatedRoadConditionType",
      values: [
        "blackIce",
        "deepSnow",
        "dry",
        "freezingOfWetRoads",
        "freezingPavements",
        "freezingRain",
        "freshSnow",
        "ice",
        "iceBuildUp",
        "iceWithWheelBarTracks",
        "icyPatches",
        "looseSnow",
        "normalWinterConditionsForPedestrians",
        "packedSnow",
        "roadSurfaceMelting",
        "slipperyRoad",
        "slushOnRoad",
        "slushStrings",
        "snowDrifts",
        "snowOnPavement",
        "snowOnTheRoad",
        "surfaceWater",
        "wet",
        "wetAndIcyRoad",
        "wetIcyPavement",
        "other",
      ],
    },
    WinterDrivingManagement: {
      element: "winterEquipmentManagementType",
      values: [
        "doNoUseStudTyres",
        "useSnowChains",
        "useSnowChainsOrTyres",
        "useSnowTyres",
        "winterEquipmentOnBoardRequired",
        "other",
      ],
    },
    RoadsideServiceDisruption: {
      element: "roadsideServiceDisruptionType",
      values: [
        "barClosed",
        "dieselShortage",
        "fuelShortage",
        "lpgShortage",
        "methaneShortage",
        "noDieselForHeavyVehicles",
        "noDieselForLightVehicles",
        "noPublicTelephones",
        "noToiletFacilities",
        "noVehicleRepairFacilities",
        "petrolShortage",
        "restAreaBusy",
        "restAreaClosed",
        "restAreaOvercrowdedDriveToAnotherRestArea",
        "serviceAreaBusy",
        "serviceAreaClosed",
        "serviceAreaFuelStationClosed",
        "serviceAreaOvercrowdedDriveToAnotherServiceArea",
        "serviceAreaRestaurantClosed",
        "someCommercialServicesClosed",
        "waterShortage",
      ],
    },
    CarParks: {
      element: "carParkConfiguration",
      values: ["multiStorey", "parkAndRide", "singleLevel", "underground"],
    },
  },
  causeTypes: [
    "accident",
    "congestion",
    "earlierAccident",
    "earlierEvent",
    "earlierIncident",
    "equipmentFailure",
    "excessiveHeat",
    "frost",
    "holidayTraffic",
    "infrastructureFailure",
    "largeNumbersOfVisitors",
    "obstruction",
    "pollutionAlert",
    "poorWeather",
    "problemsAtBorderPost",
    "problemsAtCustomPost",
    "problemsOnLocalRoads",
    "radioactiveLeakAlert",
    "roadsideEvent",
    "rubberNecking",
    "securityIncident",
    "shearWeightOfTraffic",
    "technicalProblems",
    "terrorism",
    "toxicCloudAlert",
    "vandalism",
    "other",
  ],
  severities: ["highest", "high", "medium", "low", "lowest", "none", "unknown"],
  probabilities: ["certain", "probable", "riskOf"],
} as const;
