/** WZDx 4.2 vocabularies, verbatim from the JSON schemas at github.com/usdot-jpo-ode/wzdx (tag v4.2). */
export const WZDX = {
  version: "4.2",
  eventType: ["work-zone", "detour", "restriction"],
  workTypeName: [
    "maintenance",
    "minor-road-defect-repair",
    "roadside-work",
    "overhead-work",
    "below-road-work",
    "barrier-work",
    "surface-work",
    "painting",
    "roadway-relocation",
    "roadway-creation",
  ],
  vehicleImpact: [
    "all-lanes-closed",
    "some-lanes-closed",
    "all-lanes-open",
    "alternating-one-way",
    "some-lanes-closed-merge-left",
    "some-lanes-closed-merge-right",
    "all-lanes-open-shift-left",
    "all-lanes-open-shift-right",
    "some-lanes-closed-split",
    "flagging",
    "temporary-traffic-signal",
    "unknown",
  ],
  laneStatus: [
    "open",
    "closed",
    "shift-left",
    "shift-right",
    "merge-left",
    "merge-right",
    "alternating-flow",
  ],
  laneType: [
    "general",
    "exit-lane",
    "exit-ramp",
    "entrance-lane",
    "entrance-ramp",
    "sidewalk",
    "bike-lane",
    "shoulder",
    "parking",
    "median",
    "two-way-center-turn-lane",
    "center-left-turn-lane",
  ],
  restrictionType: [
    "no-trucks",
    "travel-peak-hours-only",
    "hov-3",
    "hov-2",
    "no-parking",
    "reduced-width",
    "reduced-height",
    "reduced-length",
    "reduced-weight",
    "axle-load-limit",
    "gross-weight-limit",
    "towing-prohibited",
    "permitted-oversize-loads-prohibited",
    "local-access-only",
    "no-passing",
  ],
  relatedRoadEventType: [
    "first-in-sequence",
    "next-in-sequence",
    "first-occurrence",
    "next-occurrence",
    "related-work-zone",
    "related-detour",
    "planned-moving-operation",
    "active-moving-operation",
  ],
} as const;
