import { existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import postgres from "postgres";
import { drizzle } from "drizzle-orm/postgres-js";
import { migrate } from "drizzle-orm/postgres-js/migrator";

/**
 * Resolves the drizzle-kit migrations folder relative to the running module,
 * tolerating both layouts this code runs in:
 *  - as the published/workspace package: `dist/index.js` → `../drizzle` sibling
 *    (shipped via package `files`);
 *  - inlined into a service bundle: the service's build copies `drizzle/` next
 *    to its entry, so `./drizzle` resolves there.
 */
function resolveMigrationsFolder(): string {
  const candidates = ["../drizzle", "./drizzle"].map((rel) =>
    fileURLToPath(new URL(rel, import.meta.url))
  );
  const found = candidates.find(existsSync);
  if (!found) {
    throw new Error(`drizzle migrations folder not found (looked in: ${candidates.join(", ")})`);
  }
  return found;
}

/**
 * Creates (or replaces) the Martin-discoverable `conditions.segment_flow`
 * tile function: `ST_AsMVT` over `road_segment LEFT JOIN segment_speed`,
 * with a `min_zoom` LOD filter so low zooms only sweep major roads. Martin
 * auto-publishes any `f(z int, x int, y int, query_params json) RETURNS
 * bytea` function under its bare name, so this needs no versioned migration
 * entry (and drizzle-kit cannot model functions anyway) — just an idempotent
 * `CREATE OR REPLACE` run after every boot's `migrate(...)`.
 *
 * No `feature_id` argument to `ST_AsMVT`: MVT feature ids must be integers,
 * and `segment_id` is text, so it travels as a plain attribute instead (a
 * future client-side recolor can still `promoteId: "segment_id"`).
 */
async function applySegmentFlowTileFunction(client: postgres.Sql): Promise<void> {
  await client`
    CREATE OR REPLACE FUNCTION conditions.segment_flow(z integer, x integer, y integer, query_params json)
    RETURNS bytea AS $$
    DECLARE bounds geometry := ST_TileEnvelope(z, x, y); mvt bytea;
    BEGIN
      SELECT ST_AsMVT(t, 'segment_flow', 4096, 'geom') INTO mvt FROM (
        SELECT s.segment_id, s.dir, s.highway,
               sp.speed_ratio, sp.los, sp.confidence, sp.current_kph, sp.free_flow_kph,
               ST_AsMVTGeom(ST_Transform(s.geom, 3857), bounds, 4096, 64, true) AS geom
        FROM conditions.road_segment s
        LEFT JOIN conditions.segment_speed sp USING (segment_id)
        WHERE s.min_zoom <= z AND s.geom && ST_Transform(bounds, 4326)
      ) t WHERE t.geom IS NOT NULL;
      RETURN COALESCE(mvt, ''::bytea);
    END;
    $$ LANGUAGE plpgsql STABLE STRICT PARALLEL SAFE
  `;
}

/**
 * Applies all pending versioned migrations (generated by drizzle-kit from
 * `schema.ts`, in `packages/core/drizzle/`) to the database. Applied migrations
 * are tracked in `drizzle.__drizzle_migrations_oc` — a dedicated table so an
 * OpenConditions DB shared with another Drizzle project (e.g. OpenMapX in dev)
 * keeps separate histories. Idempotent; safe to run on every service boot.
 *
 * Takes a connection string (not a client) and opens its own short-lived
 * `max: 1` connection: drizzle's postgres-js driver replaces the client's type
 * parsers/serializers with identity functions (it does its own (de)serialization),
 * so handing it the app's shared pool would corrupt every later raw query on
 * that pool. A throwaway client is the drizzle-recommended migration pattern.
 *
 * The PostGIS extension and the `conditions` schema are created here, not in a
 * migration: drizzle-kit cannot model `CREATE EXTENSION`, and the generated
 * migrations reference `conditions.observations` + the `geometry` type, both of
 * which must already exist before the first migration runs.
 */
export async function runMigrations(connectionString: string): Promise<void> {
  const migrationsFolder = resolveMigrationsFolder();
  const client = postgres(connectionString, { max: 1 });
  try {
    // Run before drizzle(client) mutates the client's serializers (these have
    // no object/Date params, so native serialization is irrelevant anyway).
    await client`CREATE EXTENSION IF NOT EXISTS postgis`;
    await client`CREATE SCHEMA IF NOT EXISTS conditions`;
    await migrate(drizzle(client), {
      migrationsFolder,
      migrationsTable: "__drizzle_migrations_oc",
    });
    // Runs after `migrate(...)`: the function body references `road_segment`
    // and `segment_speed`, which only exist once the versioned migrations
    // above have applied.
    await applySegmentFlowTileFunction(client);
  } finally {
    await client.end();
  }
}
