import { existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import postgres from "postgres";
import { drizzle } from "drizzle-orm/postgres-js";
import { migrate } from "drizzle-orm/postgres-js/migrator";

/**
 * Resolves the drizzle-kit migrations folder relative to the running module,
 * tolerating both layouts this code runs in:
 *  - as the published/workspace package: `dist/index.js` → `../drizzle` sibling
 *    (shipped via package `files`);
 *  - inlined into a service bundle: the service's build copies `drizzle/` next
 *    to its entry, so `./drizzle` resolves there.
 */
function resolveMigrationsFolder(): string {
  const candidates = ["../drizzle", "./drizzle"].map((rel) =>
    fileURLToPath(new URL(rel, import.meta.url))
  );
  const found = candidates.find(existsSync);
  if (!found) {
    throw new Error(`drizzle migrations folder not found (looked in: ${candidates.join(", ")})`);
  }
  return found;
}

/**
 * Applies all pending versioned migrations (generated by drizzle-kit from
 * `schema.ts`, in `packages/core/drizzle/`) to the database. Applied migrations
 * are tracked in `drizzle.__drizzle_migrations_oc` — a dedicated table so an
 * OpenConditions DB shared with another Drizzle project (e.g. OpenMapX in dev)
 * keeps separate histories. Idempotent; safe to run on every service boot.
 *
 * Takes a connection string (not a client) and opens its own short-lived
 * `max: 1` connection: drizzle's postgres-js driver replaces the client's type
 * parsers/serializers with identity functions (it does its own (de)serialization),
 * so handing it the app's shared pool would corrupt every later raw query on
 * that pool. A throwaway client is the drizzle-recommended migration pattern.
 *
 * The PostGIS extension and the `conditions` schema are created here, not in a
 * migration: drizzle-kit cannot model `CREATE EXTENSION`, and the generated
 * migrations reference `conditions.observations` + the `geometry` type, both of
 * which must already exist before the first migration runs.
 */
export async function runMigrations(connectionString: string): Promise<void> {
  const migrationsFolder = resolveMigrationsFolder();
  const client = postgres(connectionString, { max: 1 });
  try {
    // Run before drizzle(client) mutates the client's serializers (these have
    // no object/Date params, so native serialization is irrelevant anyway).
    await client`CREATE EXTENSION IF NOT EXISTS postgis`;
    await client`CREATE SCHEMA IF NOT EXISTS conditions`;
    await migrate(drizzle(client), {
      migrationsFolder,
      migrationsTable: "__drizzle_migrations_oc",
    });
  } finally {
    await client.end();
  }
}
