/**
 * The event lists CAP publishers classify their alerts by, verbatim: code →
 * name. Each list is keyed in the crosswalks by the prefix a parser reads it
 * under (`II:`, `CAP-CP:`, `VTEC:`, `awareness_type:`, `SAME:`).
 */

/**
 * Deutscher Wetterdienst warning event codes (`eventCode` `II`), from the
 * DWD warning code table of 2024-02-01 and CAP DWD profile 2.1.14. Codes 40,
 * 55, 65, 75, 85, 89 and 99 also name the matching advance information
 * (Vorabinformation); both readings name one hazard.
 */
export const DWD_II_EVENTS: Readonly<Record<string, string>> = {
  "11": "BÖEN",
  "12": "WIND",
  "13": "STURM",
  "14": "Starkwind",
  "15": "Sturm",
  "16": "schwerer Sturm",
  "22": "FROST",
  "31": "GEWITTER",
  "33": "STARKES GEWITTER",
  "34": "STARKES GEWITTER",
  "36": "STARKES GEWITTER",
  "38": "STARKES GEWITTER",
  "40": "SCHWERES GEWITTER mit ORKANBÖEN",
  "41": "SCHWERES GEWITTER mit EXTREMEN ORKANBÖEN",
  "42": "SCHWERES GEWITTER mit HEFTIGEM STARKREGEN",
  "44": "SCHWERES GEWITTER mit ORKANBÖEN und HEFTIGEM STARKREGEN",
  "45": "SCHWERES GEWITTER mit EXTREMEN ORKANBÖEN und HEFTIGEM STARKREGEN",
  "46": "SCHWERES GEWITTER mit HEFTIGEM STARKREGEN und HAGEL",
  "48": "SCHWERES GEWITTER mit ORKANBÖEN, HEFTIGEM STARKREGEN und HAGEL",
  "49": "SCHWERES GEWITTER mit EXTREMEN ORKANBÖEN, HEFTIGEM STARKREGEN und HAGEL",
  "51": "WINDBÖEN",
  "52": "STURMBÖEN",
  "53": "SCHWERE STURMBÖEN",
  "54": "ORKANARTIGE BÖEN",
  "55": "ORKANBÖEN",
  "56": "EXTREME ORKANBÖEN",
  "57": "STARKWIND",
  "58": "STURM",
  "59": "NEBEL",
  "61": "STARKREGEN",
  "62": "HEFTIGER STARKREGEN",
  "63": "DAUERREGEN",
  "64": "ERGIEBIGER DAUERREGEN",
  "65": "EXTREM ERGIEBIGER DAUERREGEN",
  "66": "EXTREM HEFTIGER STARKREGEN",
  "70": "LEICHTER SCHNEEFALL",
  "71": "SCHNEEFALL",
  "72": "STARKER SCHNEEFALL",
  "73": "EXTREM STARKER SCHNEEFALL",
  "74": "SCHNEEVERWEHUNG",
  "75": "STARKE SCHNEEVERWEHUNG",
  "76": "EXTREM STARKE SCHNEEVERWEHUNG",
  "79": "LEITERSEILSCHWINGUNGEN",
  "82": "STRENGER FROST",
  "84": "GLÄTTE",
  "85": "GLATTEIS",
  "86": "EXTREMES GLATTEIS",
  "87": "MARKANTE GLÄTTE",
  "88": "TAUWETTER",
  "89": "STARKES TAUWETTER",
  "90": "GEWITTER",
  "91": "STARKES GEWITTER",
  "92": "SCHWERES GEWITTER",
  "93": "EXTREMES GEWITTER",
  "95": "SCHWERES GEWITTER mit EXTREM HEFTIGEM STARKREGEN und HAGEL",
  "96": "EXTREMES GEWITTER mit ORKANBÖEN, EXTREM HEFTIGEM STARKREGEN und HAGEL",
  "98": "TEST-WARNUNG",
  "99": "TEST-UNWETTERWARNUNG",
  "246": "UV-INDEX",
  "247": "HITZE",
  "248": "EXTREME HITZE",
};

/**
 * The Canadian CAP profile's event list (`profile:CAP-CP:Event:0.4`), with
 * the five codes the 1.0 draft adds (`fog`, `cold`, `heat`, `damBreach`,
 * `geophysical`) and 0.4's own spelling `geophyiscal`. Codes match
 * case-insensitively.
 */
export const CAP_CP_EVENTS: Readonly<Record<string, string>> = {
  admin: "administration",
  airQuality: "air quality",
  animalHealth: "animal health",
  animalDiseas: "animal disease",
  animalFeed: "animal feed",
  aviation: "aviation",
  notam: "notice to airmen",
  airspaceClos: "airspace closure",
  airportClose: "airport closure",
  aircraftCras: "aircraft crash",
  civil: "civil",
  civilEmerg: "civil emergency",
  civilEvent: "public event",
  volunteer: "volunteer request",
  crime: "criminal activity",
  dangerPerson: "dangerous person",
  homeCrime: "home crime",
  industCrime: "industrial crime",
  retailCrime: "retail crime",
  terrorism: "terrorism",
  vehicleCrime: "vehicle crime",
  animalDang: "dangerous animal",
  fire: "fire",
  wildFire: "wildfire",
  industryFire: "industrial fire",
  urbanFire: "urban fire",
  forestFire: "forest fire",
  flood: "flood",
  stormSurge: "storm surge",
  highWater: "high water level",
  overflood: "overland flow flood",
  flashFlood: "flash flood",
  damOverflow: "dam overflow",
  geophyiscal: "geophysical",
  avalanche: "avalanche",
  earthquake: "earthquake",
  landslide: "landslide",
  magnetStorm: "magnetic storm",
  tsunami: "tsunami",
  meteor: "meteorite",
  lahar: "lahar",
  lavaFlow: "lava flow",
  pyroclasFlow: "pyroclastic flow",
  pyroclaSurge: "pyroclastic surge",
  volcano: "volcano",
  volcanicAsh: "volcanic ash cloud",
  hazmat: "hazardous materials",
  chemical: "chemical hazard",
  biological: "biological hazard",
  radiological: "radiological hazard",
  explosive: "explosive hazard",
  fallObject: "falling object",
  health: "health",
  ambulance: "ambulance",
  bloodSupply: "blood supply",
  drinkingWate: "drinking water",
  foodSupply: "food & drug supply",
  hospital: "hospital",
  infectious: "infectious disease",
  ice: "ice",
  icePressure: "ice pressure",
  rpdCloseLead: "rapid closing of coastal leads",
  spclIce: "special ice",
  marine: "marine",
  freezngSpray: "freezing spray",
  galeWind: "gale wind",
  hurricFrcWnd: "hurricane force wind",
  iceberg: "iceberg",
  marineSecure: "marine security",
  nautical: "nautical incident",
  spclMarine: "special marine",
  squall: "squall",
  stormFrcWnd: "storm force wind",
  strongWind: "strong wind",
  waterspout: "waterspout",
  missingPer: "missing person",
  amber: "AMBER alert",
  missingVPer: "missing vulnerable person",
  silver: "silver alert",
  other: "other",
  plant: "plant health",
  plantInfect: "plant infectious disease",
  reminder: "preparedness reminders",
  product: "product safety",
  publicServic: "public services",
  emergFacil: "emergency support facilities",
  emergSupport: "emergency support services",
  schoolBus: "school bus",
  schoolClose: "school closure",
  schoolLock: "school lockdown",
  facility: "service or facility",
  transit: "transit",
  railway: "railway",
  train: "train accident",
  rescue: "rescue",
  road: "roadway",
  bridgeClose: "bridge closure",
  roadClose: "roadway closure",
  roadDelay: "roadway delay",
  rdCondition: "hazardous road conditions",
  traffic: "traffic report",
  roadUsage: "roadway usage condition",
  accident: "motor vehicle accident",
  storm: "storm",
  blizzard: "blizzard",
  blowingSnow: "blowing snow",
  dustStorm: "dust storm",
  freezeDrzl: "freezing drizzle",
  freezeRain: "freezing rain",
  hurricane: "hurricane",
  rainfall: "rainfall",
  thunderstorm: "thunderstorm",
  snowfall: "snowfall",
  snowSquall: "snow squall",
  tornado: "tornado",
  tropStorm: "tropical storm",
  winterStorm: "winter storm",
  weather: "weather",
  temperature: "temperature",
  arcticOut: "arctic outflow",
  coldWave: "cold wave",
  flashFreeze: "flash freeze",
  frost: "frost",
  heatWave: "heat wave",
  heatHumidity: "high heat and humidity",
  windchill: "wind chill",
  testMessage: "test message",
  utility: "utility",
  cable: "cable service",
  diesel: "diesel supply",
  electric: "electricity supply",
  gasoline: "gasoline supply",
  heatingOil: "heating oil supply",
  internet: "internet service",
  naturalGas: "natural gas supply",
  satellite: "satellite service",
  sewer: "sewer system",
  telephone: "telephone service",
  "911Service": "911 service",
  waste: "waste management",
  water: "water supply",
  wind: "wind",
  damBreach: "dam breach",
  fog: "fog",
  geophysical: "geophysical",
  cold: "cold",
  heat: "heat",
};

/**
 * NWS VTEC phenomena (NWS Directive 10-1703 and the 2025 VTEC reference),
 * read from a `VTEC` parameter; the retired codes (EH, WC, HZ, ZY) still
 * arrive in archived and long-running products.
 */
export const VTEC_PHENOMENA: Readonly<Record<string, string>> = {
  AF: "Ashfall (land)",
  AS: "Air Stagnation",
  BH: "Beach Hazard",
  BW: "Brisk Wind",
  BZ: "Blizzard",
  CF: "Coastal Flood",
  CW: "Cold Weather",
  DF: "Debris Flow",
  DS: "Dust Storm",
  DU: "Blowing Dust",
  EC: "Extreme Cold",
  EW: "Extreme Wind",
  FA: "Flood",
  FF: "Flash Flood",
  FG: "Dense Fog (land)",
  FL: "Flood (forecast point)",
  FR: "Frost",
  FW: "Fire Weather",
  FZ: "Freeze",
  GL: "Gale",
  HF: "Hurricane Force Wind",
  HT: "Heat",
  HU: "Hurricane",
  HW: "High Wind",
  HY: "Hydrologic",
  IS: "Ice Storm",
  LE: "Lake Effect Snow",
  LO: "Low Water",
  LS: "Lakeshore Flood",
  LW: "Lake Wind",
  MA: "Marine",
  MF: "Dense Fog (marine)",
  MH: "Ashfall (marine)",
  MS: "Dense Smoke (marine)",
  RB: "Small Craft for Rough Bar",
  RP: "Rip Current Risk",
  SC: "Small Craft",
  SE: "Hazardous Seas",
  SI: "Small Craft for Winds",
  SM: "Dense Smoke (land)",
  SQ: "Snow Squall",
  SR: "Storm",
  SS: "Storm Surge",
  SU: "High Surf",
  SV: "Severe Thunderstorm",
  SW: "Small Craft for Hazardous Seas",
  TO: "Tornado",
  TR: "Tropical Storm",
  TS: "Tsunami",
  TY: "Typhoon",
  UP: "(Heavy)* Freezing Spray",
  WI: "Wind",
  WS: "Winter Storm",
  WW: "Winter Weather",
  XH: "Extreme Heat",
  ZF: "Freezing Fog",
  ZR: "Freezing Rain",
  EH: "Excessive Heat",
  WC: "Wind Chill",
  HZ: "Hard Freeze",
  ZY: "Freezing Spray",
};

/**
 * MeteoAlarm awareness types (CAP profile 2.0), the number before `;` in the
 * `awareness_type` parameter; publishers spell the words differently, so
 * the number is the code. There is no 11.
 */
export const METEOALARM_AWARENESS_TYPES: Readonly<Record<string, string>> = {
  "1": "Wind",
  "2": "Snow or Ice",
  "3": "Thunderstorm",
  "4": "Fog",
  "5": "High Temperature",
  "6": "Low Temperature",
  "7": "Coastal Event",
  "8": "Forest Fire",
  "9": "Avalanche",
  "10": "Rain",
  "12": "Flood",
  "13": "Rain Flood",
  "14": "Marine Hazard",
  "15": "Drought",
};

/**
 * EAS/SAME event codes (47 CFR 11.31(e), 2026 text, and SQW, which NWS
 * assigns outside the table), read from a `SAME` event code.
 */
export const SAME_EVENTS: Readonly<Record<string, string>> = {
  EAN: "Emergency Action Notification (National only)",
  NIC: "National Information Center",
  NPT: "National Periodic Test",
  RMT: "Required Monthly Test",
  RWT: "Required Weekly Test",
  ADR: "Administrative Message",
  AVW: "Avalanche Warning",
  AVA: "Avalanche Watch",
  BZW: "Blizzard Warning",
  BLU: "Blue Alert",
  CAE: "Child Abduction Emergency",
  CDW: "Civil Danger Warning",
  CEM: "Civil Emergency Message",
  CFW: "Coastal Flood Warning",
  CFA: "Coastal Flood Watch",
  DSW: "Dust Storm Warning",
  EQW: "Earthquake Warning",
  EVI: "Evacuation Immediate",
  EWW: "Extreme Wind Warning",
  FRW: "Fire Warning",
  FFW: "Flash Flood Warning",
  FFA: "Flash Flood Watch",
  FFS: "Flash Flood Statement",
  FLW: "Flood Warning",
  FLA: "Flood Watch",
  FLS: "Flood Statement",
  HMW: "Hazardous Materials Warning",
  HWW: "High Wind Warning",
  HWA: "High Wind Watch",
  HUW: "Hurricane Warning",
  HUA: "Hurricane Watch",
  HLS: "Hurricane Statement",
  LEW: "Law Enforcement Warning",
  LAE: "Local Area Emergency",
  MEP: "Missing and Endangered Persons",
  NMN: "Network Message Notification",
  TOE: "911 Telephone Outage Emergency",
  NUW: "Nuclear Power Plant Warning",
  DMO: "Practice/Demo Warning",
  RHW: "Radiological Hazard Warning",
  SVR: "Severe Thunderstorm Warning",
  SVA: "Severe Thunderstorm Watch",
  SVS: "Severe Weather Statement",
  SPW: "Shelter in Place Warning",
  SMW: "Special Marine Warning",
  SPS: "Special Weather Statement",
  SSA: "Storm Surge Watch",
  SSW: "Storm Surge Warning",
  TOR: "Tornado Warning",
  TOA: "Tornado Watch",
  TRW: "Tropical Storm Warning",
  TRA: "Tropical Storm Watch",
  TSW: "Tsunami Warning",
  TSA: "Tsunami Watch",
  VOW: "Volcano Warning",
  WSW: "Winter Storm Warning",
  WSA: "Winter Storm Watch",
  SQW: "Snow Squall Warning",
};
